---
sidebar: sidebar 
permalink: concept_nw_internal_external.html 
keywords: ontap select, internal network, external network 
summary: 内部和外部 ONTAP Select 网络的特征。 
---
= ONTAP Select内部和外部网络
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Select 内部和外部网络的特征。



== ONTAP Select 内部网络

内部 ONTAP Select 网络仅存在于产品的多节点变体中，负责为 ONTAP Select 集群提供集群通信， HA 互连和同步复制服务。此网络包括以下端口和接口：

* * e0c ， e0d.* 托管集群网络 LIF
* 托管 RSM LIF 的 * e0e.*
* 托管 HA 互连 LIF 的 * e0f.*


此网络的吞吐量和延迟对于确定 ONTAP Select 集群的性能和故障恢复能力至关重要。为了确保集群安全并确保系统接口与其他网络流量分开，需要进行网络隔离。因此，此网络必须由 ONTAP Select 集群独占使用。


NOTE: 不支持对 Select 集群流量以外的流量使用 Select 内部网络，例如应用程序或管理流量。ONTAP 内部 VLAN 上不能存在其他 VM 或主机。

遍历内部网络的网络数据包必须位于一个专用的 VLAN 标记第 2 层网络上。可通过完成以下任务之一来完成此操作：

* 将带有 VLAN 标记的端口组分配给内部虚拟 NIC （ e0c 到 e0f ）（ VST 模式）
* 使用上游交换机提供的原生 VLAN ，其中原生 VLAN 不用于任何其他流量（分配一个没有 VLAN ID 的端口组，即 EST 模式）


在所有情况下，内部网络流量的 VLAN 标记都是在 ONTAP Select VM 之外进行的。


NOTE: 仅支持 ESX 标准和分布式 vSwitch 。不支持其他虚拟交换机或 ESX 主机之间的直接连接。内部网络必须完全打开；不支持 NAT 或防火墙。

在 ONTAP Select 集群中，内部流量和外部流量使用称为端口组的虚拟第 2 层网络对象进行分隔。正确分配这些端口组的 vSwitch 非常重要，尤其是对于负责提供集群， HA 互连和镜像复制服务的内部网络而言。如果这些网络端口的网络带宽不足，则发生原因 性能可能会下降，甚至会影响集群节点的稳定性。因此，四节点，六节点和八节点集群要求内部 ONTAP Select 网络使用 10 Gb 连接；不支持 1 Gb NIC 。但是，可以对外部网络进行权衡，因为限制传入 ONTAP Select 集群的数据流不会影响其可靠运行的能力。

双节点集群可以使用四个 1 Gb 端口传输内部流量，也可以使用一个 10 Gb 端口，而不是四节点集群所需的两个 10 Gb 端口。如果环境中的条件使服务器无法安装四个 10 Gb NIC 卡，则可将两个 10 Gb NIC 卡用于内部网络，并将两个 1 Gb NIC 用于外部 ONTAP 网络。



=== 内部网络验证和故障排除

可以使用网络连接检查程序功能验证多节点集群中的内部网络。可以从运行 `network connectivity-check start` 命令的 Deploy 命令行界面调用此功能。

运行以下命令以查看测试的输出：

[listing]
----
network connectivity-check show --run-id X (X is a number)
----
此工具仅适用于对多节点 Select 集群中的内部网络进行故障排除。不应使用此工具对单节点集群（包括 vNAS 配置）， ONTAP Deploy 到 ONTAP Select 连接或客户端连接问题进行故障排除。

集群创建向导（ ONTAP Deploy UI 的一部分）包含内部网络检查器，作为创建多节点集群期间可用的可选步骤。鉴于内部网络在多节点集群中发挥的重要作用，将此步骤作为集群创建工作流的一部分可以提高集群创建操作的成功率。

从 ONTAP Deploy 2.10 开始，内部网络使用的 MTU 大小可以设置为 7 ， 500 到 9 ， 000 之间。此外，还可以使用网络连接检查程序测试介于 7 ， 500 和 9 ， 000 之间的 MTU 大小。默认 MTU 值设置为虚拟网络交换机的值。如果环境中存在 VXLAN 等网络覆盖，则必须将此默认值替换为较小的值。



== ONTAP Select 外部网络

ONTAP Select 外部网络负责集群的所有出站通信，因此，无论是单节点配置还是多节点配置都存在。尽管此网络没有对内部网络严格定义的吞吐量要求，但管理员应注意不要在客户端和 ONTAP VM 之间创建网络瓶颈，因为性能问题可能会被错误地描述为 ONTAP Select 问题。


NOTE: 可以采用与内部流量类似的方式在 vSwitch 层（ VST ）和外部交换机层（ EST ）标记外部流量。此外， ONTAP Select VM 本身也可以在一个称为 VGT 的过程中对外部流量进行标记。请参见一节 link:concept_nw_data_mgmt_separation.html["数据和管理流量隔离"] 了解更多详细信息。

下表重点介绍了 ONTAP Select 内部网络与外部网络之间的主要区别。

* 内部网络与外部网络快速参考 *

[cols="3*"]
|===
| Description | 内部网络 | 外部网络 


| 网络服务 | 集群 HA/IC RAID SyncMirror （ RSM ） | 数据管理集群间（ SnapMirror 和 SnapVault ） 


| 网络隔离 | Required | 可选 


| 帧大小（ MTU ） | 7 ， 500 到 9 ， 000 | 1 ， 500 （默认） 9 ， 000 （支持） 


| IP 地址分配 | 已自动生成 | 用户定义的 


| DHCP 支持 | 否 | 否 
|===


=== NIC 绑定

为了确保内部和外部网络具有提供高性能和容错能力所需的带宽和故障恢复能力特性，建议使用物理网络适配器绑定。支持使用单个 10 Gb 链路的双节点集群配置。但是， NetApp 建议的最佳实践是在 ONTAP Select 集群的内部和外部网络上使用 NIC 绑定。



=== MAC 地址生成

分配给所有 ONTAP Select 网络端口的 MAC 地址由随附的部署实用程序自动生成。该实用程序使用 NetApp 专用于平台的组织唯一标识符（ Organizationally Unique Identifier ， OUI ），以确保与 FAS 系统不存在冲突。然后，此地址的副本将存储在 ONTAP Select 安装虚拟机（ ONTAP Deploy ）的内部数据库中，以防止在将来的节点部署期间意外重新分配。管理员不应修改为网络端口分配的 MAC 地址。
