---
sidebar: sidebar 
permalink: concept_vpi_overview.html 
keywords: vcenter, plug-in, vcenter plug-in, deploy plug-in, overview, functionality 
summary: 适用于 ONTAP Select Deploy 的 VMware vCenter 插件专为在 VMware 环境中工作的 ONTAP Select 管理员而设计。它可以替代原生 Deploy 用户界面。 
---
= Deploy vCenter 插件概述
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
适用于 ONTAP Select Deploy 的 VMware vCenter 插件专为在 VMware 环境中工作的 ONTAP Select 管理员而设计。它可以替代原生 Deploy 用户界面。



== 随 Deploy 打包

Deploy vCenter 插件随 Deploy 管理实用程序打包在一起。在使用 Deploy 用户界面将此插件安装到 vCenter 服务器后，您可以通过 vSphere Web 界面访问此插件。



== 与 VMware 集成

对于许多企业而言， VMware vCenter 是一个用于管理虚拟化数据中心和云资源的中央平台。由于 Deploy 插件与 vCenter 紧密集成，因此管理员可以在 ONTAP Select 和 vCenter 域之间快速移动，以利用各种资源之间的关系。



== Deploy vCenter 插件提供的功能

安装 Deploy vCenter 插件后，可通过 vSphere 在 * 全局清单列表 * 窗格中使用两个主要选项。



=== ONTAP Select 集群

ONTAP Select 集群选项大致相当于原生 Deploy Web 用户界面中的 * 集群 * 选项卡。它提供下表所述的功能。

[cols="30,70"]
|===
| 执行此操作 ... | 执行此操作 ... 


| 部署 ONTAP Select 集群 | 单击新建 ONTAP Select 。 


| 查看集群详细信息 | 选择一个集群，单击摘要，然后单击详细信息。 


| 查看集群事件消息 | 选择一个集群，单击摘要，然后单击事件。 


| 将集群联机或脱机移动，或者删除集群 | 选择一个集群，单击操作，然后单击所需的操作。 


| 启动 System Manager | 选择集群，单击摘要，单击详细信息，然后单击启动 System Manager 。 


| 查看集群使用的 ESXi 主机 | 选择一个集群，单击更多对象，然后单击主机。有关更多详细信息以及进一步操作，请选择一台主机。 


| 查看集群使用的 ONTAP VM | 选择一个集群，单击更多对象，然后单击 ONTAP VM 。有关更多详细信息以及进一步操作，请选择一个虚拟机。 


| 查看集群使用的数据存储库 | 选择一个集群，单击更多对象，然后单击数据存储库。有关更多详细信息以及进一步操作，请选择一个数据存储库。 


| 查看集群使用的网络 | 选择一个集群，单击更多对象，然后单击网络。有关更多详细信息以及进一步操作，请选择一个网络。 
|===


=== ONTAP Select 部署

ONTAP Select Deploy 选项大致相当于原生 Deploy Web 用户界面中的 * 虚拟机管理程序主机 * 和 * 管理 * 选项卡。它可通过页面顶部的三个选项卡提供功能，如下表所述。

[cols="15,85"]
|===
| 选项卡 | Description 


| 摘要 | 介绍 Deploy 实例的特征，包括主机名和 IP 地址。 


| 主机 | 显示有关已向 ONTAP Select Deploy 注册的 ESXi 主机的信息。您可以添加或删除主机。 


| 管理 | 用于通过 Deploy 实用程序执行管理任务。此功能相当于 ONTAP Select Deploy 原生 用户界面，只是插件不提供 * 凭据 * 和 * 插件 * 选项。 
|===


== 将vCenter插件与本机Deploy用户界面进行比较

通过 vSphere 提供的 vCenter 插件功能相当于原生 Deploy 用户界面。但是，插件不提供一些功能，这些功能仅在 Deploy 用户界面中可用。



=== 管理vCenter插件

您不能使用 vCenter 插件安装，更新，删除或验证 vCenter 插件。您必须通过原生 Deploy 用户界面执行这些管理任务。



=== 管理vCenter凭据

在安装 vCenter 插件之前，您必须添加必要的 vCenter 凭据，以便使用原生 Deploy 用户界面进行部署。



=== ONTAP Select 集群必须由同一个 vCenter Server 控制

您只能部署和支持由安装此插件的单个 vCenter 服务器管理的 ONTAP Select 集群。您不能使用此插件访问由其他 vCenter 服务器管理的 ONTAP Select 集群或在独立 ESXi 或 KVM 主机上运行的集群。
