---
sidebar: sidebar 
permalink: concept_automate_ansible.html 
keywords: ansible, automation, configuration management, ontap, ontap select, na_ots_deploy, na_ots_cluster, ansible roles, ansible playbook 
summary: 使用 Ansible 角色自动执行 ONTAP Select 部署。 
---
= 利用 Ansible 实现 ONTAP Select 部署自动化
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
使用 Ansible 角色和攻略手册自动执行 ONTAP Select 部署。

Ansible 角色是一个标准化文件结构中的任务，模板，处理程序和变量的逻辑集合。使用这些角色促进，重复使用和模块化可独立使用的功能。在要执行的攻略手册中包括角色以及要运行这些角色的主机列表。安装 Ansible ，更新必要的模块并了解攻略手册后，您可以从 NetApp GitHub 下载 ONTAP Select （ OTS ）角色，创建并运行您自己的攻略手册来部署 ONTAP Select 集群。



== 角色

ONTAP Select 可使用两个角色：



=== na_ots_deploy

此角色会将 ONTAP Select Deploy 的安装文件下载到 vCenter 或 ESXi 主机上。然后，它会创建并运行 Deploy VM 。

此角色使用以下输入值：

* vCenter 或 ESXi 主机凭据
* 部署 VM 创建，包括以下信息：
+
** IP 地址
** 主机名
** 登录
** Password
** 数据存储库
** 网络


* OVA 文件的本地路径
+
在运行攻略手册（包括角色）之前，请确保安装文件可用。




NOTE: 提供这些输入值的最简单方法是使用 Yml 格式的全局变量文件。在攻略手册中传递此 Yml 文件。

该角色具有一个任务，用于将 Deploy OVA 文件导入到主机，创建虚拟机并运行该虚拟机。您可以从 NetApp Ansible GitHub 访问并下载此角色，网址为： link:https://github.com/netapp-automation/na_ots_deploy["na_ots_deploy"^]



=== na_ots_cluster

此角色使用 ONTAP Select Deploy API 创建和部署 ONTAP Select 集群。它假定已创建 Deploy VM ，并且该 VM 已手动启动并正在运行，或者使用 * 角色 na_ots_deploy* 。此外，此角色还假定 Select 主机已正确配置 ONTAP Select 集群所需的网络和存储。

此角色使用 vCenter 或 ESXi 凭据的输入值，并使用 Deploy VM 凭据来访问 API 以及创建 ONTAP Select 集群和节点 VM 所需的所有相关信息。

此角色将执行以下任务：

* 添加（ vCenter 或 ESXi ）主机凭据
* 获取并注册主机 ID
* 验证内部网络（对于多节点集群）
* 正在创建集群
* 配置节点
* 配置网络和存储池
* 部署集群


因此，此角色将在集群虚拟机启动并运行且 ONTAP Select 集群完全部署的情况下完成。您可以从 NetApp Ansible GitHub 访问并下载此角色，网址为： link:https://github.com/NetApp-Automation/na_ots_cluster["na_ots_cluster"^]



== 示例攻略手册

以下是一个称为这两个 ONTAP Select 角色的示例攻略手册。请注意，输入变量在 Yml 文件中定义，并通过 "vars_files" 传递。您可以在每个角色的 README 文件中找到更多详细信息。

[listing]
----
—

– name: Create ONTAP Select deploy from OVA (ESXi)

vars_files:

– vars_deploy.yml                              # All Variables

– vars_deploy_pwd.yml                          # host_password & deploy_password

hosts: “{{ target_vcenter_or_esxi_host }}”     # Entry in Ansible ‘hosts’ file

gather_facts: false

connection: ‘local’

roles:

– na_ots_deploy

– name: Create ONTAP Select Cluster

vars_files:

– vars_cluster_test.yml

– vars_cluster_pwd.yml

hosts: “localhost”

gather_facts: false

roles:

– na_ots_cluster

----
使用上述角色创建并运行 ONTAP Select 集群后，您可以利用丰富的 ONTAP Ansible 角色集进一步自动执行 ONTAP 特性和功能。可以访问可用的 ONTAP 角色 link:https://github.com/NetApp/ansible["此处"]。总之， ONTAP Select Ansible 角色以及 ONTAP 角色可以让您完全自动化端到端工作流，以便使用 ONTAP Select 管理存储。
