---
sidebar: sidebar 
permalink: concept_adm_upgrading_nodes.html 
keywords: administer, administering, web, upgrading nodes 
summary: 部署 ONTAP Select 集群后，您可以根据需要使用标准 ONTAP 软件升级操作步骤 升级每个节点的 ONTAP 映像。 
---
= 升级ONTAP Select节点
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
部署 ONTAP Select 集群后，您可以根据需要升级集群中每个节点上的 ONTAP 映像。


CAUTION: 您不能使用 Deploy 管理实用程序升级现有 ONTAP Select 节点。Deploy 实用程序只能用于创建新的 ONTAP Select 集群。



== 常规操作步骤

总体而言，您应使用以下步骤升级现有 ONTAP Select 节点。

. 导航到 NetApp 支持站点上的下载页面。
+
https://mysupport.netapp.com/site/downloads["NetApp 支持下载"^]

. 单击 * ONTAP Select 节点升级 * 。
. 根据需要选择并下载相应的升级映像以响应所有提示。
+
在升级 ONTAP Select 节点之前，请查看追加信息 发行说明以及所有必需的过程。

. 使用带有 ONTAP Select 升级文件的标准 ONTAP 升级过程升级 ONTAP Select 节点。有关支持的升级路径的信息、请参见 link:https://docs.netapp.com/us-en/ontap/upgrade/concept_upgrade_paths.html["支持的ONTAP升级路径"^]。




== 还原ONTAP Select节点

您不能将ONTAP Select节点还原到最初安装该节点的版本之前的版本。例如：

最初安装的是ONTAP Select 9.7:: 您可以将节点升级到9.8版、然后根据需要还原回9.7版。
最初安装的是ONTAP Select 9.8:: 无法还原到9.7版、因为此版本早于最初安装的版本。




== 使用VMXNET3网络驱动程序

VMXNET3是在VMware ESXi上部署新集群时附带的默认网络驱动程序。如果升级运行ONTAP Select 9.4或更早版本的现有ONTAP Select节点、则不会自动升级网络驱动程序。您必须手动升级到 VMXNET3 。您应联系 NetApp 支持部门以获得升级方面的帮助。

.相关信息
* link:https://docs.netapp.com/us-en/ontap/upgrade/index.html["ONTAP升级概述"^]

