---
sidebar: sidebar 
permalink: concept_api_operation.html 
keywords: rest api, deploy rest api, rest, operation, basic operation 
summary: 虽然 REST 建立了一组通用的技术和最佳实践，但每个 API 的详细信息可能因设计选择而异。在使用 ONTAP Select Deploy API 之前，您应了解 API 的详细信息和操作特征。 
---
= 基本操作特征
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
虽然 REST 建立了一组通用的技术和最佳实践，但每个 API 的详细信息可能因设计选择而异。在使用 ONTAP Select Deploy API 之前，您应了解 API 的详细信息和操作特征。



== 虚拟机管理程序主机与 ONTAP Select 节点

虚拟机管理程序 host_ 是托管 ONTAP Select 虚拟机的核心硬件平台。在虚拟机管理程序主机上部署 ONTAP Select 虚拟机并使其处于活动 ONTAP Select 状态时，该虚拟机将被视为 _vp 节点 _ 。在 Deploy REST API 版本 3 中，主机和节点对象是独立的。这样就可以建立一对多关系，其中一个或多个 ONTAP Select 节点可以在同一虚拟机管理程序主机上运行。



== 对象标识符

创建每个资源实例或对象时，系统会为其分配一个唯一标识符。这些标识符在 ONTAP Select Deploy 的特定实例中具有全局唯一性。发出创建新对象实例的 API 调用后，相关 ID 值将返回到 HTTP 响应的 `location` 标头中的调用程序。在引用资源实例时，您可以提取此标识符并在后续调用中使用它。


NOTE: 对象标识符的内容和内部结构可以随时更改。仅当引用关联对象时，才应根据需要在适用的 API 调用上使用标识符。



== 请求标识符

每个成功的 API 请求都会分配一个唯一标识符。此标识符将在关联 HTTP 响应的 `requis-id` 标头中返回。您可以使用请求标识符来统称单个特定 API 请求响应事务的活动。例如，您可以根据请求 ID 检索事务的所有事件消息。



== 同步和异步调用

服务器执行从客户端收到的 HTTP 请求的主要方式有两种：

* 同步服务器将立即执行请求，并使用状态代码 200 ， 201 或 204 进行响应。
* 异步服务器接受请求并使用状态代码 202 进行响应。这表示服务器已接受客户端请求并启动后台任务来完成此请求。最终成功或失败不会立即出现，必须通过其他 API 调用来确定。




== 确认已完成长时间运行的作业

通常，任何可能需要很长时间才能完成的操作都会在服务器上使用后台任务异步处理。使用 Deploy REST API 时，每个后台任务都会通过一个作业对象进行锁定，此作业对象会跟踪任务并提供信息，例如当前状态。创建后台任务后，将在 HTTP 响应中返回作业对象，包括其唯一标识符。

您可以直接查询作业对象以确定关联 API 调用的成功或失败。有关追加信息 ，请参见 _asynchronous processing using the Job objection_ 。

除了使用作业对象之外，您还可以通过其他方法来确定请求的成功或失败，包括：

* 事件消息您可以使用原始响应返回的请求 ID 检索与特定 API 调用关联的所有事件消息。事件消息通常包含成功或失败的指示，在调试错误情况时也很有用。
* 资源状态或状态多个资源会保留一个状态或状态值，您可以查询此值以间接确定请求的成功或失败。




== 安全性

Deploy API 使用以下安全技术：

* 传输层安全性通过网络在 Deploy 服务器和客户端之间发送的所有流量均通过 TLS 加密。不支持在未加密的通道上使用 HTTP 协议。支持 TLS 1.2 版。
* HTTP 身份验证基本身份验证用于每个 API 事务。每个请求都会添加一个 HTTP 标头，其中包含 base64 字符串中的用户名和密码。

