---
sidebar: sidebar 
permalink: concept_vpi_planning.html 
keywords: vcenter, plug-in, vcenter plug-in, deploy plug-in, planning 
summary: 在安装和使用 Deploy vCenter 插件之前，您应做好准备以确保成功。 
---
= 规划使用 Deploy vCenter 插件
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
在安装和使用 Deploy vCenter 插件之前，您应做好准备以确保成功。



== 软件要求

您应考虑下表所述的几个软件要求。

[cols="35,65"]
|===
| 软件 | 支持的版本 


| ONTAP Select Deploy 实用程序 | 2.11.2 或更高版本 


| VMware vSphere | 6.5 GA 或更高版本 


| VMware vSphere 用户界面 | HTML5 （不支持基于闪存的版本） 


| ESXi | 6.5U2 或更高版本 
|===


== 集群大小限制

下表介绍了与集群大小相关的一些限制，您应考虑这些限制。

[cols="35,65"]
|===
| 项目 | 支持的最大数量 


| ONTAP Select 部署集群 | 100 


| 节点（虚拟机） | 1000 


| 主机 | 800 
|===


== vCenter 用户帐户的 RBAC 特权

管理和访问此插件需要多种不同的 vCenter 特权。这些权限对应于以下三个类别中的操作：

* 通过 Deploy 管理插件：
+
** 安装
** 升级
** 删除


* 通过 vSphere 客户端访问此插件
* 验证用户通过 vSphere 对插件的访问权限


请参见 link:concept_vpi_manage_before.html#preparing-the-vcenter-server-accounts["准备 vCenter Server 帐户"] 有关详细信息 ...



== AutoSupport 限制

Deploy vCenter 插件可在 Deploy 管理实用程序（包括插件 URL ）中提供最低使用量信息。但是， AutoSupport 中包含一个已安装插件的表，可通过 AutoSupport 查看器显示这些插件。


NOTE: 您不能使用 Deploy 插件通过 vSphere Web Client 下载 AutoSupport 软件包。您必须使用原生 Deploy 界面下载 AutoSupport 软件包。



== 其他限制

在安装和使用 Deploy vCenter 插件之前，还应考虑其他一些限制：

* 每个 vCenter 插件实例仅支持一个 vCenter 服务器。
* 不支持在链接模式下配置的 vCenter 服务器。
* vSphere 中的 Deploy 插件图形用户界面仅显示由同一 vCenter Server 管理的 ONTAP Select 虚拟机的集群。不包括在独立 ESXi 和 KVM 主机上运行的 ONTAP Select 集群。

