---
sidebar: sidebar 
permalink: concept_nw_concepts_chars.html 
keywords: ontap select, networking concepts, cluster characteristics 
summary: 首先，熟悉适用于 ONTAP Select 环境的一般网络概念。然后，了解单节点和多节点集群的具体特征和选项。 
---
= 网络连接：一般概念和特征
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
首先，熟悉适用于 ONTAP Select 环境的一般网络概念。然后，了解单节点和多节点集群的具体特征和选项。



== 物理网络

物理网络主要通过提供底层第二层交换基础架构来支持 ONTAP Select 集群部署。与物理网络相关的配置包括虚拟机管理程序主机和更广泛的交换网络环境。



=== 主机 NIC 选项

每个 ONTAP Select 虚拟机管理程序主机都必须配置两个或四个物理端口。您选择的确切配置取决于多种因素，包括：

* 集群包含一个或多个 ONTAP Select 主机
* 使用的是什么虚拟机管理程序操作系统
* 如何配置虚拟交换机
* 链路是否使用 LACP




=== 物理交换机配置

您必须确保物理交换机的配置支持 ONTAP Select 部署。物理交换机与基于虚拟机管理程序的虚拟交换机集成在一起。您选择的确切配置取决于多种因素。主要注意事项包括：

* 如何在内部网络和外部网络之间保持隔离？
* 您是否会在数据网络和管理网络之间保持隔离？
* 如何配置第二层 VLAN ？




== 逻辑网络连接

ONTAP Select 使用两个不同的逻辑网络，根据类型分隔流量。具体而言，流量可以在集群中的主机之间流动，也可以流向存储客户端和集群外的其他计算机。虚拟机管理程序管理的虚拟交换机有助于支持逻辑网络。



=== 内部网络

在多节点集群部署中，各个 ONTAP Select 节点使用隔离的 " 内部 " 网络进行通信。此网络不会在 ONTAP Select 集群中的节点之外公开或可用。


NOTE: 只有多节点集群存在内部网络。

内部网络具有以下特征：

* 用于处理 ONTAP 集群内流量，包括：
+
** 集群
** 高可用性互连（ HA-IC ）
** RAID 同步镜像（ RSM ）


* 基于 VLAN 的单个第 2 层网络
* 静态 IP 地址由 ONTAP Select 分配：
+
** 仅 IPv4
** 未使用 DHCP
** 链路本地地址


* 默认情况下， MTU 大小为 9000 字节，可在 7500-9000 范围（包括在内）内进行调整




=== 外部网络

外部网络处理 ONTAP Select 集群节点与外部存储客户端以及其他计算机之间的流量。外部网络是每个集群部署的一部分，具有以下特征：

* 用于处理 ONTAP 流量，包括：
+
** 数据（ NFS ， CIFS ， iSCSI ）
** 管理（集群和节点；可选 SVM ）
** 集群间（可选）


* 也可以支持 VLAN ：
+
** 数据端口组
** 管理端口组


* 根据管理员的配置选择分配的 IP 地址：
+
** IPv4 或 IPv6


* 默认情况下， MTU 大小为 1500 字节（可调整）


外部网络包含所有大小的集群。



== 虚拟机网络环境

虚拟机管理程序主机可提供多种网络功能。

ONTAP Select 依靠虚拟机提供的以下功能：

虚拟机端口:: ONTAP Select 可使用多个端口。它们会根据多种因素进行分配和使用，包括集群的大小。
虚拟交换机:: 虚拟机管理程序环境中的虚拟交换机软件（无论是 vSwitch （ VMware ）还是 Open vSwitch （ KVM ））将虚拟机公开的端口与物理以太网 NIC 端口连接起来。您必须根据环境的具体情况为每个 ONTAP Select 主机配置 vSwitch 。

