---
sidebar: sidebar 
permalink: concept_lic_cp_operation.html 
keywords: license, licensing, capacity pools, operation details 
summary: 容量池许可模式与容量层模式不同。存储容量将分配给一个池并在多个节点之间共享，而不是为每个节点分配专用存储容量。我们还创建了其他组件和流程来支持容量池模型。 
---
= ONTAP Select容量池许可模式的操作详细信息
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
容量池许可模式与容量层模式不同。存储容量将分配给一个池并在多个节点之间共享，而不是为每个节点分配专用存储容量。我们还创建了其他组件和流程来支持容量池模型。



== 许可证管理器

License Manager会在每个Deploy管理实用程序实例中作为一个单独的进程运行。LM 提供的一些功能包括：

* 根据容量池许可证序列号为每个节点生成唯一的 20 位序列号
* 根据 ONTAP Select 节点的请求，从共享容量池创建容量租约
* 通过 Deploy 用户界面报告池使用情况信息




== 租约特征

使用容量池许可证为节点上的每个数据聚合分配的存储必须具有关联的租约。节点请求存储租约，如果有可用容量，则 License Manager 将以租约的形式做出响应。每个租约都具有以下显式或隐式属性：

* 许可证管理器每个 ONTAP Select 节点都与一个许可证管理器实例关联
* 容量池每个 ONTAP Select 节点都与一个容量池相关联
* 存储分配租约中会分配特定的容量值
* 到期日期和时间租约的持续时间介于一小时到七天之间，具体取决于用户配置。




== 许可证锁定 ID

License Manager 的每个实例以及相应的每个 Deploy 实用程序实例都使用一个唯一的 128 位编号进行标识。此数量与九位数的容量池许可证序列号相结合，可将池锁定到特定的 License Manager 实例（实际上是一个 Deploy 实例）。在生成 NetApp 许可证文件（ NLF ）过程中，您必须在 NetApp 支持站点上提供这两个值。

您可以通过以下方式使用 Web 用户界面确定 Deploy 实例的许可证锁定 ID ：

* 开始使用页面首次登录到 Deploy 时，将显示此页面。您也可以通过单击页面右上角的下拉框并选择 Getting Started 来显示此页面。LLID 将显示在 Add Licenses 部分中。
* 管理单击页面顶部的 * 管理 * 选项卡 A ，然后单击 * 系统 * 和 * 设置 * 。




== 基本租赁操作

每次创建，扩展或更改数据聚合时， ONTAP Select 节点都必须找到或请求有效的容量租约。可以使用从先前请求中获取但仍然有效的租约，也可以根据需要请求新租约。ONTAP Select 节点会执行以下步骤来查找容量池租约：

. 如果节点上存在现有租约，则只要符合以下所有条件，就会使用此租约：
+
** 租约未过期
** 聚合的存储请求不超过租约容量


. 如果找不到现有租约，则节点将从 License Manager 请求新租约。




== 将存储容量归还给容量池

存储容量可根据需要从容量池中分配，每个新请求都会减少池中的可用存储。在以下几种情况下，存储容量会返回到池中：

* 数据聚合的租约到期，节点不会续订
* 已删除数据聚合



NOTE: 如果删除了 ONTAP Select 虚拟机，则任何活动租约将一直有效，直到到期为止。发生这种情况时，容量将返回到池。
