---
sidebar: sidebar 
permalink: concept_vpi_manage_before.html 
keywords: vcenter, plug-in, vcenter plug-in, deploy plug-in, manage, managing 
summary: 在安装和管理 Deploy vCenter 插件之前，您需要执行以下几项操作。 
---
= 开始之前
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
在安装和管理 Deploy vCenter 插件之前，您需要执行以下几项操作。



== 确定是使用 Deploy Web 用户界面还是使用命令行界面

在大多数情况下，在管理 vCenter 插件时， Deploy Web 用户界面是最方便的选项，本指南中介绍了此选项。但是，您也可以使用 Deploy 命令行界面管理此插件。有关详细信息，请在 Deploy 命令行界面提示符处键入以下命令：

* `d部署插件？` （子命令包括： install ， remove ， show 和 update ）
* `deDeploy plugin-packages show` …




== 所有管理任务通用的准备工作

无论执行何种管理任务，您都必须执行几个步骤。常见准备工作包括：

* 阅读 " 开始熟悉 Deploy vCenter 插件 " 一节。
* 确保 ONTAP Select Deploy 管理实用程序已安装并正在运行。有关详细信息，请参见《 VMware 安装和集群部署指南》。
* 获取帐户凭据：
+
** 部署管理员帐户
** vCenter Server 帐户


* 确保 Deploy 实用程序可以通过网络访问 vCenter 服务器上的端口 443 。


根据管理任务的不同，可能需要进行其他准备。



== 准备 vCenter Server 帐户

在安装和使用 Deploy 插件之前，您必须使用所需权限创建 vCenter 帐户。您可以创建一个具有所有必要权限的帐户，也可以创建多个具有一个权限的帐户。为简单起见，以下示例将 vCenter 特权分布在三个不同的角色中，然后可以将这些角色分配给三个相应的帐户。



==== 验证最终用户对插件的访问权限

您需要一个帐户来验证通过 vSphere 对插件的访问权限。此帐户必须具有以下 vCenter 权限： sessions.validate.session 。在 vCenter 中创建帐户后，您必须将其定义到 Deploy 管理实用程序中。在 Deploy Web 用户界面中，单击 Administration 选项卡，然后单击 Credentials 以提供 vCenter Server 位置和凭据。

此帐户的使用方式如下：

* 命名的 vCenter Server 将在插件注册对话框窗口中用作安装目标。
* 安装此插件后， Deploy 会使用此帐户来验证 vSphere 用户访问此插件的请求。




==== 管理插件

在 Deploy Web 用户界面中，您可以安装此插件，然后升级或删除它。每次执行其中一项管理操作时，系统都会在弹出窗口中提示您输入 vCenter 帐户。每个管理操作都通过一个单独的 vCenter 权限进行控制。

要安装，升级和删除此插件，您必须分配以下权限：

* 扩展
+
** 注册扩展
** 更新扩展
** 取消注册扩展




您可以创建一个具有全部三个特权的角色和帐户，也可以根据需要在多个帐户之间划分这些特权。



==== 访问此插件

最终用户可以通过 vSphere 访问此插件。您必须为要使用此插件的帐户分配以下权限：

* NetApp
+
** ONTAP Select 部署
+
*** 管理员





