---
sidebar: sidebar 
permalink: reference_plan_ots_hardware.html 
keywords: plan, planning, vmware, hardware, hardware requirements 
summary: 与 VMware 环境相关，您应考虑几个硬件要求和规划问题。 
---
= ONTAP Select VMware虚拟机管理程序和硬件注意事项
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
与 VMware 环境相关，您应考虑几个硬件要求和规划问题。



== 虚拟机管理程序要求

与运行 ONTAP Select 的虚拟机管理程序相关的要求有多种。


NOTE: 你应该复习一下link:reference_release_notes.html["《 ONTAP Select 发行说明》"]任何其他已知的限制或约束。



=== VMware 许可

要部署 ONTAP Select 集群，您的组织必须为运行 ONTAP Select 的虚拟机管理程序主机拥有有效的 VMware vSphere 许可证。您应使用适合您的部署的许可证。



=== 软件兼容性

您可以在 KVM 和 ESXi 虚拟机管理程序上部署ONTAP Select 。

[role="tabbed-block"]
====
.KVM
--
ONTAP Select支持以下 KVM 虚拟机管理程序版本：

* Red Hat Enterprise Linux 9.6、9.5、9.4、9.2、9.1、9.0、8.8、8.7 和 8.6 上的 KVM
* Rocky Linux 9.6、9.5、9.4、9.3、9.2、9.1、9.0、8.9、8.8、8.7 和 8.6 上的 KVM


--
.ESXi
--
ONTAP Select支持以下 ESXi 虚拟机管理程序版本：

* VMware ESXi 9.0
* VMware ESXi 8.0 U3
* VMware ESXi 8.0 U2
* VMware ESXi 8.0 U1 (内部版本21495797)
* VMware ESXi 8.0 GA (内部版本20513097)



NOTE: 只要 VMware 仍支持相同的版本， NetApp 就支持在确定的 ESXi 版本上使用 ONTAP Select 。


NOTE: ESXi 7.0 GA 已停止提供服务。如果您有使用此版本的ONTAP Select集群，则必须按照以下说明升级到受支持的版本： https://mysupport.netapp.com/matrix["互操作性表工具（ IMT ）"^] 。

--
====


=== VMware vCenter 和独立 ESXi 主机

如果 ESXi 虚拟机管理程序主机由 vCenter Server 管理，则必须使用 vCenter 凭据将此主机注册到 Deploy 管理实用程序。您不能使用 ESXi 凭据将主机注册为独立主机。



== 核心硬件要求

部署 ONTAP Select 的物理虚拟机管理程序主机必须满足多个硬件要求。您可以为虚拟机管理程序主机选择任何平台，只要该主机满足最低硬件要求即可。以下供应商提供受支持的硬件平台： Cisco ， Dell ， HP ， Fujitsu ， Lenovo ， 和 Supermicro 。


NOTE: 从ONTAP Select 9.9.1 开始，仅支持基于 Intel Xeon Sandy Bridge 或更高版本的 CPU 型号。

有关详细信息、请参见 https://mysupport.netapp.com/matrix["互操作性表工具、window=_blank"]。



=== 基本硬件要求

无论节点实例类型或许可证提供如何，适用于所有平台的常见硬件要求都有几项。

.处理器
支持的微处理器包括用于服务器的 Intel Xeon 处理器，请参阅link:https://www.intel.com/content/www/us/en/products/processors/xeon/view-all.html?Processor+Type=1003["Intel Xeon 处理器， window=_blank"]了解更多信息。


NOTE: ONTAP Select不支持高级微设备(AMD)处理器。

.以太网配置
根据集群大小、可以使用多种受支持的以太网配置。

[cols="2,3,3"]
|===
| 集群大小 | 最低要求 | 建议的要求 


| 单节点集群 | 2个1GbE | 2 个 10GbE 


| 双节点集群或MetroCluster SDS | 4个1GbE或1个10GbE | 2 个 10GbE 


| 四节点、六节点、八节点、十节点或十二节点集群 | 2 个 10GbE | 4个10GbE或2个25/40GbE 
|===


=== 根据实例类型确定的其他硬件要求

根据节点实例类型，还需要满足多项其他硬件要求。

请参见 link:concept_lic_platforms.html["了解平台许可证产品"] 有关详细信息 ...

[cols="a1,a2,a2,a2"]
|===
| 节点大小 | CPU 核心 | 内存 | 所需的平台许可证产品 


| 小型 | 六个或更多物理核心，其中四个保留用于ONTAP Select | 24 GB 或更大，其中 16 GB 预留给ONTAP Select | 标准型、高级型或高级 XL 型 


| 中等 | 十个或更多物理核心，其中八个保留用于ONTAP Select | 72GB 或更大，其中 64GB 预留给ONTAP Select | Premium 或 Premium XL 


| 大型 | 十八个或更多物理核心，其中十六个保留用于ONTAP Select | 136GB 或更大，其中 128GB 预留给ONTAP Select | 高级版 xl 
|===

NOTE: 根据平台许可证，还有其他磁盘要求。请参见 link:reference_plan_ots_storage.html["存储和 RAID"] 有关详细信息 ...
