---
sidebar: sidebar 
permalink: reference_new_ots.html 
keywords: new features 
// summary: The current release includes several new features and improvements specific to ONTAP Select. 
summary: 当前版本包括ONTAP Select的几项新增功能或改进功能。 
---
= ONTAP Select的新增功能
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
了解受支持的ONTAP Select版本中的新增功能和增强功能。



== ONTAP Select 9.17.1

ONTAP Select 9.17.1 包含多项新功能和改进。

KVM 主机上本地连接的 NVMe 磁盘的软件 RAID 支持:: ONTAP Select 9.17.1 引入了对基于内核的虚拟机 (KVM) 虚拟机管理程序主机上ONTAP Select本地连接的 NVMe 磁盘的软件 RAID 支持。
+
--
要对本地连接的 NVMe 磁盘使用软件 RAID，您需要link:kvm-host-configuration-and-preparation-checklist.html["配置 PCI 直通（DirectPath IO）"]当您准备 KVM 主机时。这为 KVM 主机提供了对本地连接的 NVMe 磁盘的直接访问，这是以下任务所必需的：

* 配置 KVM 主机以使用 NVMe 驱动器
* 部署集群后使用软件 RAID


link:concept_stor_swraid_local.html["了解本地连接存储的软件 RAID 配置服务"] 。

--
支持KVM主机集群扩容和缩容:: 从ONTAP Select 9.17.1 开始，基于内核的虚拟机 (KVM) 和 ESXi 虚拟机管理程序主机均支持集群扩展和收缩功能。对于ONTAP Select 9.16.1 和 9.15.1，仅 ESXi 虚拟机管理程序主机支持集群扩展和收缩功能。
+
--
您可以使用现有ONTAP Select集群上的集群扩展和收缩功能将集群规模从六节点增加到八节点，或者将集群规模从八节点减少到六节点。

link:task_cluster_expansion_contraction.html["了解集群扩展和收缩以及支持的 KVM 和 ESXi 虚拟机管理程序版本"] 。

--
增强对 ESXi 主机上的集群扩展和收缩的支持:: 从ONTAP Select 9.17.1 开始，ESXi 主机上的六节点集群和十二节点集群之间支持集群扩展和收缩：
+
--
--
您可以按以下增量增加现有 ESXi 群集的群集大小：

* 从六个节点到八个、十个或十二个节点
* 从八个节点到十个或十二个节点
* 从十到十二个节点


您可以按以下增量减少现有 ESXi 群集的群集大小：

* 从十二个节点到十个、八个或六个节点
* 从十个节点到八个或六个节点
* 从八个节点到六个节点


--
link:task_cluster_expansion_contraction.html["了解集群扩展和收缩以及支持的 KVM 和 ESXi 虚拟机管理程序版本"] 。

--
支持ONTAP功能:: 从ONTAP Select 9.17.1 开始， ONTAP Select支持以下许可的ONTAP功能：
+
--
* SnapLock Select
+
从ONTAP Select 9.17.1 开始，新部署将自动获得SnapLock Select 许可。对于从ONTAP Select 9.16.1 及更早版本升级，您需要SnapLocklink:https://mysupport.netapp.com/site/["NetApp 支持站点"^]并手动应用它。

* SnapMirror云
+
从ONTAP Select 9.17.1 开始， ONTAP Select支持SnapMirror云。SnapMirrorSnapMirror是一项获得许可的ONTAP功能，在部署ONTAP Select 9.17.1 集群或将现有ONTAP Select集群升级到 9.17.1 版本时默认启用。

+
https://docs.netapp.com/us-en/ontap/concepts/snapmirror-cloud-backups-object-store-concept.html["了解SnapMirror云备份到对象存储"^] 。



--
在多节点集群上支持 vSAN ESA:: 从ONTAP Select 9.17.1 开始，对 vSAN Express 存储架构 (ESA) 的支持得到扩展，以部署多节点集群。此增强功能使您能够部署 vSAN ESA 配置。
+
--
vSAN ESA 是一种 ESX 特定配置，是 vSphere 8 中引入的 VMware vSAN 的新架构。vSAN ESA 旨在提供增强的效率、可扩展性和性能，尤其是在使用基于 NVMe 的 TLC 闪存设备时。

ONTAP Select Deploy 和ONTAP Select for ESX 支持配置ONTAP Select单节点和多节点集群，使用 vSAN 或外部阵列类型的数据存储作为其存储池。

[NOTE]
====
要执行内容库操作，您需要访问额外的权限级别。如果您使用受限角色，则这对于 vSAN ESA 部署是必需的。

link:https://docs.netapp.com/us-en/ontap-select/reference_plan_dep_vmware.html["了解内容库操作的访问权限级别"^] 。

====
--
更新了 NDA 驱动程序支持:: 从ONTAP Select 9.17.1 开始，FreeBSD NDA（NVMe 直接访问）设备驱动程序取代了 NVD（NVMe 快速磁盘驱动程序）。FreeBSD驱动程序通过实施 NVMe 命令协议来支持直接访问设备。当您部署ONTAP Select 9.17.1 集群或将现有ONTAP Select集群升级到 9.17.1 版本时，配置 NVMe 设备时会默认启动 FreeBSD 驱动程序。
+
--
对于ONTAP Select 9.16.1 及更早版本，NVD 将继续为ONTAP Select部署中的 NVMe 设备提供支持。

--
已更新KVM虚拟机管理程序支持:: 从ONTAP Select 9.17.1 开始，Red Hat Enterprise Linux (RHEL) 9.6 和 Rocky Linux 9.6 支持 KVM 虚拟机管理程序。




== ONTAP Select 9.16.1.

ONTAP Select 9.16.1提供了几项新功能和改进功能。

更新了NetApp许可证文件支持:: 从ONTAP Select 9.161开始、更新了NetApp许可证文件(NLG)支持。新的NLL格式包括ARP、ONTAP S3和S3 SnapMirror功能的许可证。link:reference_lic_ontap_features.html#ontap-features-automatically-enabled-by-default["了解更多信息。"](英文)
+
--
对于新的ONTAP Select 9.16.1 Deploy、将自动应用新的NLG格式。将现有ONTAP Select Deploy升级到9.161时、不会应用新的NLG格式。要获取ARP、ONTAP S3和S3 SnapMirror功能许可证、必须在升级后下载更新的NLG。如果还原到ONTAP Select 9.151或更早版本、则必须重新安装升级之前拥有的功能许可证。

--
支持自动防兰森功能:: ONTAP Select 9.161引入了对自动防兰软件保护(ARP)的支持。ONTAP Select 9.161仅支持手动更新ARP、不支持自动更新。ONTAP Select 9.161的NLL中包含ARP功能许可证。link:reference_lic_ontap_features.html#ontap-features-automatically-enabled-by-default["了解更多信息。"](英文)
增强了对VMware ESXi的支持:: ONTAP Select 9.16.1支持VMware ESXi 8.0 U3。
已更新KVM虚拟机管理程序支持:: 从ONTAP Select 9.16.1 开始，RHEL 9.5 和 Rocky Linux 9.5 支持 KVM 虚拟机管理程序。




== ONTAP Select 9.15.1.

ONTAP Select 9.15.1提供了几项新功能和改进功能。

已更新KVM虚拟机管理程序支持:: 从ONTAP Select 9.15.1开始、RHEL 9.4和洛基Linux 9.4支持基于内核的虚拟机(Kerner-Based Virtual Machine、KVM)虚拟机管理程序。
支持集群扩展和缩减:: 从ONTAP Select 9.15.1开始、支持集群扩展和缩减。
+
--
* 将集群从六节点扩展为八节点集群
+
您可以通过集群扩展功能将集群大小从六节点集群增加到八节点集群。目前不支持将集群从一节点、双节点或四节点集群扩展为六节点或八节点集群。link:task_cluster_expansion_contraction.html#expand-the-cluster["了解更多信息。"](英文)

* 将八节点集群缩减为六节点集群
+
您可以通过集群缩减功能将集群大小从八节点集群减小为六节点集群。目前不支持将集群从六节点或八节点集群缩写为一节点、两节点或四节点集群。link:task_cluster_expansion_contraction.html#contract-the-cluster["了解更多信息。"](英文)



--



NOTE: 对集群扩展和缩减的支持仅限于ESX集群。



== ONTAP Select 9.14.1

ONTAP Select 9.14.1提供了几项新功能和改进功能。

支持KVM虚拟机管理程序:: 从ONTAP Select 9.14.1开始、已恢复对KVM虚拟机管理程序的支持。以前、ONTAP Select 9.10.1不再支持在KVM虚拟机管理程序上部署新集群、而ONTAP Select 9.11.1不再支持管理现有KVM集群和主机(脱机或删除除外)。
不再支持部署VMware vCenter插件:: 从ONTAP Select 9.14.1开始、不再支持Deploy VMware vCenter插件。
更新了ONTAP Select Deploy支持:: 如果您运行的ONTAP Select Deploy 9.14.1版本低于9.14.1P2、则应尽快升级到ONTAP Select Deploy 9.14.1P2。有关详细信息，请参见 link:https://library.netapp.com/ecm/ecm_download_file/ECMLP2886733["ONTAP Select 9.14.1发行说明"^]。
增强了对VMware ESXi的支持:: ONTAP Select 9.14.1支持VMware ESXi 8.0 U2。




== ONTAP Select 9.13.1.

ONTAP Select 9.13.1提供了几项新功能和改进功能。

支持基于TCP的NVMe:: 升级到ONTAP Select 9.13.1时、您必须具有新许可证才能支持基于TCP的NVMe。首次从9.131版部署ONTAP Select时、系统会自动包含此许可证。
已更新VMware ESXi支持:: 从ESXi .13.1开始、ONTAP 9 8.0.1 GA (内部版本20513097)在硬件版本4及更高版本中受支持。
更新了ONTAP Select Deploy支持:: 自2024年4月起、ONTAP Select Deploy 9.13.1不再适用于NetApp 支持站点。如果您运行的是ONTAP Select Deploy 9.13.1,则应尽快升级到ONTAP Select Deploy 9.14.1P2。有关详细信息，请参见 link:https://library.netapp.com/ecm/ecm_download_file/ECMLP2886733["ONTAP Select 9.14.1发行说明"^]。




== ONTAP Select 9.12.1

ONTAP Select 9.12.1从当前版本的核心ONTAP 产品中的大多数新开发中受益。它不包括ONTAP Select 特有的任何新功能或改进。

自2024年4月起、ONTAP Select Deploy 9.12.1不再适用于NetApp 支持站点。如果您运行的是ONTAP Select Deploy 9.12.1、则应尽快升级到ONTAP Select Deploy 9.14.1P2。有关详细信息，请参见 link:https://library.netapp.com/ecm/ecm_download_file/ECMLP2886733["ONTAP Select 9.14.1发行说明"^]。



== ONTAP Select 9.11.1

ONTAP Select 9.11.1包括多项新功能和改进功能。

增强了对VMware ESXi的支持:: ONTAP Select 9.11.1支持VMware ESXi 7.0 U3C。
支持 VMware NSX-T:: ONTAP Select 9.10.1及更高版本已通过VMware NSX-T 3.1.2的认证。将NSX-T与使用OVA文件和ONTAP Select Deploy管理实用程序部署的ONTAP Select 单节点集群结合使用时、不存在任何功能问题或缺陷。但是、在将NSX-T与ONTAP Select 多节点集群结合使用时、您应注意ONTAP Select 9.11.1的以下限制：
+
--
* 网络连接检查程序
+
在基于 NSX-T 的网络上运行 Deploy CLI 提供的网络连接检查程序时，此检查程序将失败。



--
不再支持 KVM 虚拟机管理程序::
+
--
* 从ONTAP Select 9.10.1开始、您无法再在KVM虚拟机管理程序上部署新集群。
* 从ONTAP Select 9.11.1开始、除了脱机和删除功能之外、现有KVM集群和主机不再具有所有易管理性功能。
+
NetApp强烈建议客户计划并执行从适用于KVM的ONTAP Select 到任何其他ONTAP 平台的完整数据迁移、包括适用于ESXi的ONTAP Select。有关详细信息，请参见 https://mysupport.netapp.com/info/communications/ECMLP2877451.html["EOA通知"^]



--




== ONTAP Select 9.10.1

ONTAP Select 9.10.1包括多项新功能和改进功能。

支持 VMware NSX-T:: ONTAP Select 9.10.1 已通过 VMware NSX-T 3.1.2 的认证。将NSX-T与使用OVA文件和ONTAP Select Deploy管理实用程序部署的ONTAP Select 单节点集群结合使用时、不存在任何功能问题或缺陷。但是，在将 NSX-T 与 ONTAP Select 多节点集群结合使用时，应注意以下要求和限制：
+
--
* 集群 MTU
+
在部署集群之前，您必须手动将集群 MTU 大小调整为 8800 ，以考虑额外的开销。VMware 准则允许在使用 NSX-T 时使用 200 字节的缓冲区

* 网络 4x10 Gb 配置
+
对于在配置有四个 NIC 的 VMware ESXi 主机上部署 ONTAP Select 的情况， Deploy 实用程序将提示您遵循最佳实践，即在两个不同的端口组之间拆分内部流量，并在两个不同的端口组之间拆分外部流量。但是，在使用覆盖网络时，此配置不起作用，您应忽略此建议。在这种情况下，您只能使用一个内部端口组和一个外部端口组。

* 网络连接检查程序
+
在基于 NSX-T 的网络上运行 Deploy CLI 提供的网络连接检查程序时，此检查程序将失败。



--
不再支持 KVM 虚拟机管理程序:: 从 ONTAP Select 9.10.1 开始，您无法再在 KVM 虚拟机管理程序上部署新集群。但是，如果您将集群从先前版本升级到 9.10.1 ，则仍可使用 Deploy 实用程序管理集群。




== ONTAP Select 9.9.1

ONTAP Select 9.9.1包括多项新功能和改进功能。

处理器系列支持:: 从ONTAP Select 9.9.1开始、ONTAP Select仅支持Intel Xeon桑迪桥或更高版本的CPU型号。
已更新VMware ESXi支持:: ONTAP Select 9.1.1增强了对VMware ESXi的支持。现在支持以下版本：
+
--
* ESXi 7.0 U2
* ESXi 7.0 U1


--




== ONTAP Select 9.8

ONTAP Select 9.8提供了几项新增功能和变更功能。

高速接口:: 此高速接口功能可同时为25G (25GbE)和40G (40GbE)提供一个选项、从而增强了网络连接。要在使用这些较高速度时获得最佳性能、您应遵循ONTAP Select 文档中所述的端口映射配置最佳实践。
已更新VMware ESXi支持:: ONTAP Select 9.8中有关VMware ESXi支持的两项更改。
+
--
* 支持ESXi 7.0 (GA内部版本15843807及更高版本)
* 不再支持ESXi 6.0


--

