---
sidebar: sidebar 
permalink: reference_plan_ots_two_node.html 
keywords: plan, planning, two nodes, two node clusters 
summary: 使用 HA 部署双节点集群所涉及的规划和配置与其他集群节点配置所使用的规划和配置相同。但是，在创建双节点集群时，您应注意几个不同之处。 
---
= 具有 HA 的 ONTAP Select 双节点集群
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
使用 HA 部署双节点集群所涉及的规划和配置与其他集群节点配置所使用的规划和配置相同。但是，在创建双节点集群时，您应注意几个不同之处。

.目标环境
双节点集群由一个 HA 对组成，专为远程办公室和分支机构部署而设计。


NOTE: 虽然主要针对远程办公室和分支机构环境而设计，但您也可以根据需要在数据中心部署双节点集群。

.许可
您可以使用任何 VMware vSphere 许可证部署双节点集群。但是， VMware ROBO 标准版和高级版许可证非常适合远程办公室和分支机构部署。

.调解器服务
如果集群包含两个节点，则在节点出现故障或失去通信时，无法达到所需的仲裁。为了解决这些类型的脑裂问题， ONTAP Select Deploy 实用程序的每个实例都包含一个调解器服务。此服务连接到活动双节点集群中的每个节点，以监控 HA 对并协助管理故障。调解器服务会在与每个双节点集群关联的专用 iSCSI 目标上维护 HA 状态信息。


CAUTION: 如果您有一个或多个活动双节点集群，则管理这些集群的 ONTAP Select Deploy 虚拟机必须始终处于运行状态。如果 Deploy 虚拟机暂停或出现故障，则调解器服务将不可用，并且双节点集群的 HA 功能将丢失。

.集群和调解器服务的位置
由于双节点集群通常部署在远程办公室或分支机构中，因此它们可以与企业数据中心和提供管理支持的 Deploy 实用程序处于远程位置。使用此配置时， Deploy 实用程序和集群之间的管理流量将通过 WAN 传输。有关限制和限制的详细信息，请参见发行说明。

.备份Deploy配置数据
最佳做法是定期备份 Deploy 配置数据，包括在创建集群后备份。对于双节点集群来说，这一点尤为重要，因为备份中包含调解器配置数据。

.分配给 Deploy 的静态 IP 地址
您必须为 Deploy 管理实用程序分配一个静态 IP 地址。此要求适用场景 All Deploy 实例用于管理一个或多个 ONTAP Select 双节点集群。
