---
sidebar: sidebar 
permalink: reference_new_ots.html 
keywords: new features 
// summary: The current release includes several new features and improvements specific to ONTAP Select. 
summary: 当前版本包括ONTAP Select的几项新增功能或改进功能。 
---
= 此版本中的新增功能
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp会定期更新ONTAP Select 、为您提供新功能和增强功能。



== ONTAP Select 9.15.1.

ONTAP Select 9.15.1提供了几项新功能和改进功能。

已更新KVM虚拟机管理程序支持:: 从ONTAP Select 9.151开始、Red Hat Enterprise Linux (RHEL) 9.4和Rock-Linux 9.4支持基于内核的虚拟机(Kerner-Based Virtual Machine、KVM)虚拟机管理程序。
支持集群扩展和缩减:: 从ONTAP Select 9.15.1开始、支持集群扩展和缩减。
+
--
* 将集群从六节点扩展为八节点集群
+
您可以通过集群扩展功能将集群大小从六节点集群增加到八节点集群。目前不支持将集群从一节点、双节点或四节点集群扩展为六节点或八节点集群。link:task_cluster_expansion_contraction.html#expand-the-cluster["了解更多信息。"](英文)

* 将八节点集群缩减为六节点集群
+
您可以通过集群缩减功能将集群大小从八节点集群减小为六节点集群。目前不支持将集群从六节点或八节点集群缩写为一节点、两节点或四节点集群。link:task_cluster_expansion_contraction.html#contract-the-cluster["了解更多信息。"](英文)



--



NOTE: 对集群扩展和缩减的支持仅限于ESX集群。



== ONTAP Select 9.14.1

ONTAP Select 9.14.1提供了几项新功能和改进功能。

支持KVM虚拟机管理程序:: 从ONTAP Select 9.14.1开始、已恢复对KVM虚拟机管理程序的支持。以前、ONTAP Select 9.10.1不再支持在KVM虚拟机管理程序上部署新集群、而ONTAP Select 9.11.1不再支持管理现有KVM集群和主机(脱机或删除除外)。
不再支持部署VMware vCenter插件:: 从ONTAP Select 9.14.1开始、不再支持Deploy VMware vCenter插件。
更新了ONTAP Select Deploy支持:: 如果您运行的ONTAP Select Deploy 9.14.1版本低于9.14.1P2、则应尽快升级到ONTAP Select Deploy 9.14.1P2。有关详细信息，请参见 link:https://library.netapp.com/ecm/ecm_download_file/ECMLP2886733["ONTAP Select 9.14.1发行说明"^]。
增强了对VMware ESXi的支持:: ONTAP Select 9.14.1支持VMware ESXi 8.0.2。




== ONTAP Select 9.13.1.

ONTAP Select 9.13.1提供了几项新功能和改进功能。

支持基于TCP的NVMe:: 升级到ONTAP Select 9.13.1时、您必须具有新许可证才能支持基于TCP的NVMe。首次从9.131版部署ONTAP Select时、系统会自动包含此许可证。
已更新VMware ESXi支持:: 从ESXi .13.1开始、ONTAP 9 8.0.1 GA (内部版本20513097)在硬件版本4及更高版本中受支持。
更新了ONTAP Select Deploy支持:: 自2024年4月起、ONTAP Select Deploy 9.13.1不再适用于NetApp 支持站点。如果您运行的是ONTAP Select Deploy 9.13.1,则应尽快升级到ONTAP Select Deploy 9.14.1P2。有关详细信息，请参见 link:https://library.netapp.com/ecm/ecm_download_file/ECMLP2886733["ONTAP Select 9.14.1发行说明"^]。




== ONTAP Select 9.12.1

ONTAP Select 9.12.1从当前版本的核心ONTAP 产品中的大多数新开发中受益。它不包括ONTAP Select 特有的任何新功能或改进。

自2024年4月起、ONTAP Select Deploy 9.12.1不再适用于NetApp 支持站点。如果您运行的是ONTAP Select Deploy 9.12.1、则应尽快升级到ONTAP Select Deploy 9.14.1P2。有关详细信息，请参见 link:https://library.netapp.com/ecm/ecm_download_file/ECMLP2886733["ONTAP Select 9.14.1发行说明"^]。



== ONTAP Select 9.11.1

ONTAP Select 9.11.1包括多项新功能和改进功能。

增强了对VMware ESXi的支持:: ONTAP Select 9.11.1支持VMware ESXi 7.0 U3C。
支持 VMware NSX-T:: ONTAP Select 9.10.1及更高版本已通过VMware NSX-T 3.1.2的认证。将NSX-T与使用OVA文件和ONTAP Select Deploy管理实用程序部署的ONTAP Select 单节点集群结合使用时、不存在任何功能问题或缺陷。但是、在将NSX-T与ONTAP Select 多节点集群结合使用时、您应注意ONTAP Select 9.11.1的以下限制：
+
--
* 网络连接检查程序
+
在基于 NSX-T 的网络上运行 Deploy CLI 提供的网络连接检查程序时，此检查程序将失败。



--
不再支持 KVM 虚拟机管理程序::
+
--
* 从ONTAP Select 9.10.1开始、您无法再在KVM虚拟机管理程序上部署新集群。
* 从ONTAP Select 9.11.1开始、除了脱机和删除功能之外、现有KVM集群和主机不再具有所有易管理性功能。
+
NetApp强烈建议客户计划并执行从适用于KVM的ONTAP Select 到任何其他ONTAP 平台的完整数据迁移、包括适用于ESXi的ONTAP Select。有关详细信息，请参见 https://mysupport.netapp.com/info/communications/ECMLP2877451.html["EOA通知"^]



--




== ONTAP Select 9.10.1

ONTAP Select 9.10.1包括多项新功能和改进功能。

支持 VMware NSX-T:: ONTAP Select 9.10.1 已通过 VMware NSX-T 3.1.2 的认证。将NSX-T与使用OVA文件和ONTAP Select Deploy管理实用程序部署的ONTAP Select 单节点集群结合使用时、不存在任何功能问题或缺陷。但是，在将 NSX-T 与 ONTAP Select 多节点集群结合使用时，应注意以下要求和限制：
+
--
* 集群 MTU
+
在部署集群之前，您必须手动将集群 MTU 大小调整为 8800 ，以考虑额外的开销。VMware 准则允许在使用 NSX-T 时使用 200 字节的缓冲区

* 网络 4x10 Gb 配置
+
对于在配置有四个 NIC 的 VMware ESXi 主机上部署 ONTAP Select 的情况， Deploy 实用程序将提示您遵循最佳实践，即在两个不同的端口组之间拆分内部流量，并在两个不同的端口组之间拆分外部流量。但是，在使用覆盖网络时，此配置不起作用，您应忽略此建议。在这种情况下，您只能使用一个内部端口组和一个外部端口组。

* 网络连接检查程序
+
在基于 NSX-T 的网络上运行 Deploy CLI 提供的网络连接检查程序时，此检查程序将失败。



--
不再支持 KVM 虚拟机管理程序:: 从 ONTAP Select 9.10.1 开始，您无法再在 KVM 虚拟机管理程序上部署新集群。但是，如果您将集群从先前版本升级到 9.10.1 ，则仍可使用 Deploy 实用程序管理集群。




== ONTAP Select 9.9.1

ONTAP Select 9.9.1包括多项新功能和改进功能。

处理器系列支持:: 从ONTAP Select 9.9.1开始、ONTAP Select仅支持Intel Xeon桑迪桥或更高版本的CPU型号。
已更新VMware ESXi支持:: ONTAP Select 9.1.1增强了对VMware ESXi的支持。现在支持以下版本：
+
--
* ESXi 7.0 U2
* ESXi 7.0 U1


--




== ONTAP Select 9.8

ONTAP Select 9.8提供了几项新增功能和变更功能。

高速接口:: 此高速接口功能可同时为25G (25GbE)和40G (40GbE)提供一个选项、从而增强了网络连接。要在使用这些较高速度时获得最佳性能、您应遵循ONTAP Select 文档中所述的端口映射配置最佳实践。
已更新VMware ESXi支持:: ONTAP Select 9.8中有关VMware ESXi支持的两项更改。
+
--
* 支持ESXi 7.0 (GA内部版本15843807及更高版本)
* 不再支持ESXi 6.0


--

