---
sidebar: sidebar 
permalink: reference_plan_dep_general.html 
keywords: plan, planning, ontap select deploy, general requirements 
summary: 在规划安装 ONTAP Select Deploy 管理实用程序时，您应考虑几个一般要求。 
---
= ONTAP Select Deploy 的一般要求和规划
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
在规划安装 ONTAP Select Deploy 管理实用程序时，您应考虑几个一般要求。



== 将 Deploy 实用程序与 ONTAP Select 集群配对

在将 Deploy 实用程序实例与 ONTAP Select 集群配对时，您可以选择多种方法。


NOTE: 在所有部署情形下，一个 ONTAP Select 集群和集群中的节点只能由一个 Deploy 管理实用程序实例管理。一个集群不能由两个或更多不同的 Deploy 实用程序实例管理。

.每个 ONTAP Select 集群一个实用程序实例
您可以使用一个专用的 Deploy 实用程序实例部署和管理每个 ONTAP Select 集群。在这种一对一配置中，每个实用程序到集群对之间都有明确的分隔。此配置可为较小的故障域提供高级别的隔离。

.一个实用程序实例，用于多个 ONTAP Select 集群
您可以使用一个 Deploy 实用程序实例在组织中部署和管理多个 ONTAP Select 集群。在这种一对多配置中，所有处理和配置数据都由同一个 Deploy 实用程序实例管理。


NOTE: 一个 Deploy 实用程序实例最多可管理 400 个 ONTAP Select 节点或 100 个集群。



== 与KVM环境相关的要求

在KVM虚拟机管理程序环境中安装Deploy管理实用程序之前、您应查看基本要求并做好部署准备。

.部署的要求和限制
在KVM环境中安装ONTAP Select Deploy实用程序时、应考虑若干要求和限制。

.Linux KVM主机服务器硬件要求
Linux KVM虚拟机管理程序主机必须满足几项最低资源要求。验证部署ONTAP Select的主机是否满足以下基本要求：

* Linux服务器：
+
** 硬件和软件必须为64位
** 服务器必须遵循为ONTAP Select节点定义的受支持版本


* 虚拟 CPU （ 2 个）
* 虚拟内存(4 GB)
* 存储(40 GB)
* "已启用动态主机配置协议(DHCP)(您也可以分配静态IP地址)


.网络连接
验证是否已配置Deploy虚拟机网络接口、并且该接口是否可连接到其管理的ONTAP Select主机。

.支持 IP 版本 4
ONTAP Select Deploy 仅支持 IP 版本 4 （ IPv4 ）。不支持 IP 版本 6 （ IPv6 ）。此限制在以下方面影响 ONTAP Select ：

* 您必须为Deploy虚拟机的管理LIF分配IPv4地址。
* Deploy 无法创建配置为在 ONTAP LIF 上使用 IPv6 的 ONTAP Select 节点。




== 所需的配置信息

在部署规划中，您应在安装 ONTAP Select Deploy 管理实用程序之前确定所需的配置信息。

.Deploy虚拟机的名称
要用于虚拟机的名称。

.Linux KVM主机的名称
安装了Deploy实用程序的Linux KVM主机。

.存储池的名称
存放VM文件的存储池(大约需要40 GB)。

.虚拟机的网络
Deploy虚拟机所连接的网络。



== 可选网络配置信息

默认情况下、Deploy虚拟机使用DHCP进行配置。但是、如果需要、您可以手动配置虚拟机的网络接口。

.主机名
主机的名称。

.主机 IP 地址
静态IPv4地址。

.子网掩码
子网络掩码、基于虚拟机所属的网络。

.网关
默认网关或路由器。

.主 DNS 服务器
主域名服务器。

.二级 DNS 服务器
辅助域名服务器。

.搜索域
要使用的搜索域。



== 使用凭据存储进行身份验证

ONTAP Select Deploy凭据存储是一个用于保存帐户信息的数据库。在集群创建和管理过程中， Deploy 会使用帐户凭据执行主机身份验证。您应了解在规划 ONTAP Select 部署时如何使用凭据存储。


NOTE: 帐户信息将使用 AES 加密算法和 SHA-256 哈希算法安全地存储在数据库中。

.凭据类型
支持以下类型的凭据：

* 在将 ONTAP Select 节点直接部署到 VMware ESXi 期间，用于对虚拟机管理程序主机进行身份验证的主机
* 当主机由 VMware vCenter 管理时，在将 ONTAP Select 节点部署到 ESXi 时， vCenter 用于对 vCenter 服务器进行身份验证


.访问
在使用 Deploy 执行常规管理任务（例如添加虚拟机管理程序主机）时，可以在内部访问凭据存储。您也可以直接通过 Deploy Web 用户界面和 CLI 管理凭据存储。
