---
sidebar: sidebar 
permalink: reference_plan_ots_two_node.html 
keywords: plan, planning, two nodes, two node clusters 
summary: 使用 HA 部署双节点集群所涉及的规划和配置与其他集群节点配置所使用的规划和配置相同。但是，在创建双节点集群时，您应注意几个不同之处。 
---
= 具有 HA 的 ONTAP Select 双节点集群
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
使用 HA 部署双节点集群所涉及的规划和配置与其他集群节点配置所使用的规划和配置相同。但是，在创建双节点集群时，您应注意几个不同之处。

.目标环境
双节点集群由一个 HA 对组成，专为远程办公室和分支机构部署而设计。


NOTE: 虽然主要针对远程办公室和分支机构环境而设计，但您也可以根据需要在数据中心部署双节点集群。

.许可
您可以使用任何 VMware vSphere 许可证部署双节点集群。但是， VMware ROBO 标准版和高级版许可证非常适合远程办公室和分支机构部署。

.调解器服务
如果集群包含两个节点，则在节点出现故障或失去通信时，无法达到所需的仲裁。为了解决这些类型的脑裂问题， ONTAP Select Deploy 实用程序的每个实例都包含一个调解器服务。此服务连接到活动双节点集群中的每个节点，以监控 HA 对并协助管理故障。调解器服务会在与每个双节点集群关联的专用 iSCSI 目标上维护 HA 状态信息。


CAUTION: 如果您有一个或多个活动的双节点集群，则管理这些集群的ONTAP Select Deploy 虚拟机必须始终处于运行状态。如果ONTAP Select Deploy 虚拟机停止运行或发生故障，则中介服务不可用，并且双节点集群的 HA 功能将丢失。

.集群和调解器服务的位置
由于双节点集群通常部署在远程或分支机构，因此它们可能远离企业数据中心和提供管理支持的ONTAP Select Deploy 实用程序。通过这种配置， ONTAP Select Deploy 实用程序和集群之间的管理流量将通过 WAN 传输。有关限制和约束的更多信息，请参阅发行说明。

. 为ONTAP Select Deploy 分配静态 IP 地址


您必须为ONTAP Select Deploy 管理实用程序分配静态 IP 地址。此要求适用于管理一个或多个ONTAP Select双节点集群的所有ONTAP Select Deploy 实例。
