---
sidebar: sidebar 
permalink: reference_plan_ots_mcc_sds.html 
keywords: plan, planning, metrocluster, metrocluster sds 
summary: 在规划 MetroCluster ONTAP Select 部署时，您应考虑多项要求。 
---
= 准备 MetroCluster SDS 部署
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
在创建双节点 ONTAP Select 集群时， MetroCluster SDS 是一个配置选项。它与远程办公室 / 分支机构（ ROBO ）部署类似，但两个节点之间的距离最远可达 10 公里这种增强型双节点部署提供了其他用例场景。在准备部署 MetroCluster SDS 时，您应了解相关要求和限制。

在部署 MetroCluster SDS 之前，必须确保满足以下要求。

.许可
每个节点都必须具有高级或更高的 ONTAP Select 许可证。

.虚拟机管理程序平台
MetroCluster SDS 可以部署在 ROBO 环境中双节点集群所支持的同一 VMware ESXi 和 KVM 虚拟机管理程序上。

[NOTE]
====
* 从ONTAP Select 9.10.1开始、您无法再在KVM虚拟机管理程序上部署新集群。
* 从ONTAP Select 9.11.1开始、除了脱机和删除功能之外、现有KVM集群和主机不再具有所有易管理性功能。


====
.网络配置：
参与站点之间需要第 2 层连接。支持 10GbE 和 1GbE ，包括以下配置：

* 1 个 10GbE
* 4 个 1GbE



NOTE: 提供数据的端口和互连端口必须连接到第一个交换机。

.节点之间的延迟
两个节点之间的网络必须支持 5 毫秒的平均延迟，并额外支持 5 毫秒的定期抖动。在部署集群之前，您必须使用中所述的操作步骤 测试网络 link:concept_nw_concepts_chars.html["深度剖析网络"] 部分。

.调解器服务
与所有双节点 ONTAP Select 集群一样， Deploy 虚拟机中也包含一个单独的调解器服务，用于监控节点并协助管理故障。借助 MetroCluster SDS 提供的增强距离，可在网络拓扑中创建三个不同的站点。调解器与节点之间的链路往返延迟应为 125 毫秒或更短。

.存储
使用 HDD 和 SSD 磁盘均支持直连存储（ DAS ）。此外，还支持 vNAS ，包括 VMware 环境中的外部存储阵列和 vSAN 。


NOTE: 部署 MetroCluster SDS 时，不能在分布式或 " 延伸型 " 拓扑中使用 vSAN 。

.分配给 Deploy 的静态 IP 地址
您必须为 Deploy 管理实用程序分配一个静态 IP 地址。此要求适用场景 All Deploy 实例用于管理一个或多个 ONTAP Select 双节点集群。
