---
sidebar: sidebar 
permalink: reference_plan_ots_storage.html 
keywords: plan, planning, storage, software raid, hardware raid, raid, nvme 
summary: 您应考虑几个与 ONTAP Select 主机存储相关的规划问题。 
---
= ONTAP Select存储和RAID注意事项
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您应考虑几个与 ONTAP Select 主机存储相关的规划问题。


NOTE: 中概述了外部存储支持信息 link:reference_plan_ots_vnas.html["ONTAP Select vNAS 要求"]。



== 硬件 RAID 控制器要求

部署 ONTAP Select 的虚拟机管理程序主机上的 RAID 控制器必须满足多项要求。


NOTE: 运行ONTAP Select的主机在使用随ONTAP Select提供的硬件RAID控制器或软件RAID功能时需要本地物理驱动器。如果使用 ONTAP Select vNAS 解决方案 访问外部存储，则不会使用本地 RAID 控制器和软件 RAID 功能。

RAID 控制器的最低要求包括：

* 12 Gbps 吞吐量
* 512 MB 内部电池供电缓存或闪存（超级容量）缓存
* 在回写模式下配置：
+
** 启用故障恢复模式以 " 直写 " （如果支持）
** 启用 " 始终预读 " 策略（如果支持）


* RAID 控制器后面的所有本地磁盘都应配置为一个 RAID 组；如果需要，可以使用多个 RAID 控制器：
+
** 禁用 RAID 组的本地驱动器缓存，这对于保持数据完整性至关重要。


* 必须根据以下准则执行 LUN 配置：
+
** 如果RAID组大小超过最大LUN大小64 TB、则应配置多个大小相等的LUN、这些LUN占用RAID组中的所有可用存储空间。
** 如果RAID组大小小于最大LUN大小64 TB、则应配置一个LUN、此LUN占用此RAID组中的所有可用存储。






== 软件 RAID 要求

在虚拟机管理程序上部署ONTAP Select集群时、您可以使用ONTAP Select提供的软件RAID功能、而不是本地硬件RAID控制器。在使用软件 RAID 部署集群之前，您必须了解一些要求和限制。



=== 一般要求

软件RAID部署环境必须满足以下核心要求：

* VMware ESXi 8.0 GA（内部版本 20513097）或更高版本
* ONTAP Select 高级许可证或更高版本
* 仅限本地 SSD 驱动器
* 将系统磁盘与根聚合和数据聚合分离
* 主机上无硬件 RAID 控制器



NOTE: 如果存在硬件 RAID 控制器，请参见 link:concept_stor_concepts_chars.html["深度剖析存储"] 第节、了解其他配置要求。



=== ESXi特定要求

* VMware ESXi 8.0 GA（内部版本 20513097）或更高版本
* 不支持 VMware VMotion ， HA 和 DRS
* 您不能对从ONTAP Select 9.4或更早版本升级的节点使用软件RAID。如果出现这种情况、您需要为软件RAID部署创建一个新节点。




=== KVM特定要求

此外、还需要满足特定的软件包配置要求。查看link:https://docs.netapp.com/us-en/ontap-select/kvm-host-configuration-and-preparation-checklist.html#prepare-linux-server["Linux 服务器的准备"]步骤获取更多信息。

KVM的介质要求:: 使用的SSD闪存存储设备必须满足以下附加要求：
+
--
* SSD设备必须通过以下方法准确、持久地向Linux主机报告自身情况：
+
** # cat /sys/block/jue/queue <device>/ rotational
+
为这些命令报告的值必须为"0"。



* 设备应连接到HBA、或者在某些情况下连接到配置为在JBOD模式下运行的RAID控制器。使用RAID控制器时、必须在不覆盖任何RAID功能的情况下通过主机传递设备功能。在JBOD模式下使用RAID控制器时、您应查看RAID文档或根据需要联系供应商、以确保设备将转速报告为"0"。
* 有两个单独的存储组件：
+
** 虚拟机存储
+
此LVM池(存储池)包含用于托管ONTAP Select虚拟机的系统数据。LVM池必须由高持久性闪存设备作为后备存储、并且可以是SAS、SATA或NVMe。建议使用NVMe设备以提高性能。

** 数据磁盘
+
这是一组用于数据管理的SAS或SATA SSD驱动器。SSD设备应为企业级且持久耐用。不支持NVMe接口。



* 所有设备都必须使用512BPS进行格式化。


--




=== ONTAP Select 节点配置

您必须按如下所示配置每个 ONTAP Select 节点和虚拟机管理程序主机，以便将系统磁盘与根聚合和数据聚合分开：

* 创建系统存储池您必须为 ONTAP Select 系统数据创建存储池。在配置 ONTAP Select 节点时，您必须连接存储池。
* 连接必要的物理磁盘虚拟机管理程序主机必须连接所需的 SSD 磁盘，并且这些磁盘可供 ONTAP Select 虚拟机使用。这些驱动器用于存放根聚合和数据聚合。在配置 ONTAP Select 节点时，您必须连接存储磁盘。




== 存储容量限制

在规划 ONTAP Select 部署时，您应了解与存储分配和使用相关的限制。

下面介绍了最重要的存储限制。您还应查看link:https://mysupport.netapp.com/matrix/["互操作性表工具"^]以了解更多详细信息。


TIP: ONTAP Select 会对存储分配和使用实施多项限制。在部署 ONTAP Select 集群或购买许可证之前，您应熟悉这些限制。请参见 link:https://docs.netapp.com/us-en/ontap-select/concept_lic_evaluation.html["许可证"] 部分、了解更多信息。



=== 计算原始存储容量

ONTAP Select 存储容量对应于连接到 ONTAP Select 虚拟机的虚拟数据和根磁盘的总允许大小。分配容量时应考虑这一点。



=== 单节点集群的最小存储容量

为单节点集群中的节点分配的最小存储池大小为：

* 评估： 500 GB
* 生产： 1.0 TB


生产部署的最小分配量包括 1 TB 的用户数据，加上各种 ONTAP Select 内部流程使用的 266 GB ，这是必需的开销。



=== 多节点集群的最小存储容量

为多节点集群中的每个节点分配的存储池的最小大小为：

* 评估： 1.9 TB
* 生产： 2.0 TB


生产部署的最小分配量包括 2 TB 的用户数据，加上各种 ONTAP Select 内部流程使用的 266 GB ，这是必需的开销。

[NOTE]
====
HA 对中的每个节点都必须具有相同的存储容量。

在估算HA对的存储量时、必须考虑所有聚合(根聚合和数据聚合)均已镜像。因此、聚合的每个丛会占用相等的存储量。

例如、创建2 TB聚合时、它会将2 TB分配给两个丛实例(2 TB用于plex0、2 TB用于plex1)、或者分配许可总存储量的4 TB。

====


=== 存储容量和多个存储池

使用本地直连存储， VMware vSAN 或外部存储阵列时，您可以将每个 ONTAP Select 节点配置为最多使用 400 TB 的存储。但是，使用直连存储或外部存储阵列时，单个存储池的最大大小为 64 TB 。因此，如果您计划在这些情况下使用 64 TB 以上的存储，则必须按如下所示分配多个存储池：

* 在集群创建过程中分配初始存储池
* 通过分配一个或多个额外存储池来增加节点存储



NOTE: 每个存储池会保留 2% 的未使用缓冲区，并且不需要容量许可证。除非指定了容量上限，否则 ONTAP Select 不会使用此存储。如果指定了容量上限，则会使用该存储容量，除非指定的容量位于 2% 缓冲区区域中。要防止在尝试分配存储池中的所有空间时偶尔发生错误，需要使用此缓冲区。



=== 存储容量和 VMware vSAN

使用 VMware vSAN 时，数据存储库可能会大于 64 TB 。但是，在创建 ONTAP Select 集群时，您最初只能分配最多 64 TB 的容量。创建集群后，您可以从现有 vSAN 数据存储库分配更多存储。ONTAP Select 可以使用的 vSAN 数据存储库容量取决于所设置的 VM 存储策略。



=== 最佳实践

对于虚拟机管理程序核心硬件，您应考虑以下建议：

* 一个ONTAP Select聚合中的所有驱动器类型都应相同。例如，不应在同一聚合中混用 HDD 和 SSD 驱动器。




== 根据平台许可证确定的其他磁盘驱动器要求

您选择的驱动器会受到平台许可证的限制。


NOTE: 使用本地 RAID 控制器和驱动器以及软件 RAID 时，需要满足磁盘驱动器要求。这些要求不适用于通过 ONTAP Select vNAS 解决方案 访问的外部存储。

.标准
* 8 到 60 个内部 HDD （ NL-SAS ， SATA ， 10K SAS ）


.高级版
* 8 到 60 个内部 HDD （ NL-SAS ， SATA ， 10K SAS ）
* 4 到 60 个内部 SSD


.高级版 xl
* 8 到 60 个内部 HDD （ NL-SAS ， SATA ， 10K SAS ）
* 4 到 60 个内部 SSD
* 4 到 14 个内部 NVMe



NOTE: 高级许可证（仅 SSD ）和高级 XL 许可证（ SSD 或 NVMe ）支持带有本地 DAS 驱动器的软件 RAID 。



== 采用软件 RAID 的 NVMe 驱动器

您可以将软件 RAID 配置为使用 NVMe SSD 驱动器。您的环境必须满足以下要求：

* 使用受支持的部署管理实用程序ONTAP Select
* 高级 XL 平台许可证或 90 天评估许可证
* VMware ESXi 8.0 或更高版本
* 符合规格 1.0 或更高版本的 NVMe 设备


在使用 NVMe 驱动器之前，您需要手动配置这些驱动器。请参见 link:task_chk_nvme_configure.html["将主机配置为使用NVMe驱动器"] 有关详细信息 ...
