---
sidebar: sidebar 
permalink: reference_lic_ontap_features.html 
keywords: license, licensing, ontap features, default ontap features 
summary: ONTAP Select 完全支持大多数ONTAP 功能。在部署集群时、每个节点都会自动获得许多ONTAP 功能的许可。但是、某些功能需要单独的许可证。 
---
= ONTAP Select支持ONTAP功能
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Select支持大多数ONTAP功能。部署集群时，许多ONTAP功能都会自动为每个节点授予许可。但是，某些功能需要单独的许可证。


NOTE: ONTAP Select 通常不支持具有特定于硬件的依赖关系的ONTAP 功能。



== 默认情况下获得许可的 ONTAP 功能

默认情况下、ONTAP Select支持并许可以下ONTAP功能：

* 自主防兰软件(ARP)(手动更新)
* CIFS
* 重复数据删除和数据压缩
* 使用密钥管理互操作性协议 (KMIP) 进行外部密钥管理
+
外部密钥管理是 ONTAP Select 唯一支持的密钥管理。了解 link:https://docs.netapp.com/us-en/ontap/encryption-at-rest/configure-netapp-volume-encryption-concept.html["启用和配置外部密钥管理"^]。

* FlexCache
+
ONTAP Select 支持具有回写功能的 FlexCache 缓存卷。不支持具有回写功能的 FlexCache 原始卷。

+
link:concept_ots_overview.html#flexcache-write-back-with-ontap-select["详细了解使用 ONTAP Select 的 FlexCache 回写"]

* FlexClone
* iSCSI
* NDMP
* NetApp 卷加密（仅限非受限国家或地区）
* NFS
* 基于TCP的NVMe
* ONTAP 多租户功能
* ONTAP S3
* S3 SnapMirror
* SnapLock Select
+
SnapLock Select 是专为 ONTAP Select 设计的 ONTAP SnapLock 实施，包括 SnapLock Enterprise。它不包括 SnapLock Compliance。

+
link:https://docs.netapp.com/us-en/ontap/snaplock/index.html["了解 ONTAP SnapLock"^]

* SnapMirror
* SnapMirror 云
* SnapRestore
* SnapVault
* Storage VM灾难恢复(SVM DR)
+
ONTAP Select 支持 SVM DR 作为源和目标，最多可有 16 个关系。SVM DR 支持仅限于使用源 ONTAP 版本到版本 +2。例如，ONTAP Select 9.16.1 源可以连接到目标 ONTAP 版本 9.16.1、9.17.1 或 9.18.1。





== 单独许可的ONTAP 功能

对于默认情况下未获得许可的任何 ONTAP 功能，您需要获得单独的许可，包括：

* FabricPool
+

NOTE: 使用StorageGRID时、不需要FabricPool许可证。

* MetroCluster SDS （ ONTAP Select 高级许可证产品）


.相关信息
* link:concept_ots_overview.html#compare-ontap-select-and-ontap-9["请比较ONTAP Select和ONTAP 9"]
* link:https://mysupport.netapp.com/site/systems/master-license-keys["了解 NetApp ONTAP 主许可证密钥"^]

