---
sidebar: sidebar 
permalink: reference_plan_ots_vnas.html 
keywords: plan, planning, vnas 
summary: 在使用 ONTAP Select vNAS 时，您应考虑几个规划问题。 
---
= ONTAP Select vNAS 要求
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Select vNAS 是一种解决方案 ，允许 ONTAP Select 数据存储库位于运行 ONTAP Select 虚拟机的虚拟机管理程序主机外部。这些远程数据存储库可通过 VMware vSAN 或通用外部存储阵列进行访问。



== 基本要求和限制

ONTAP Select vNAS 解决方案 可用于任何大小的 ONTAP Select 集群。

所有相关存储组件（包括硬件，软件和功能要求）都必须符合中所述的要求
link:https://mysupport.netapp.com/matrix/["NetApp 互操作性表工具"^]。此外、ONTAP Select还支持VMware存储/SAN兼容性文档中所述的所有外部存储阵列、包括iSCSI、NAS (NFSv3)、光纤通道和以太网光纤通道。外部阵列支持受 ONTAP Select 支持的 ESXi 版本限制。

使用 ONTAP Select vNAS 部署集群时，支持以下 VMware 功能：

* VMotion
* 高可用性（ HA ）
* 分布式资源计划程序（ DRS ）



NOTE: 单节点和多节点 ONTAP Select 集群支持这些 VMware 功能。部署多节点集群时，应确保同一集群中的两个或更多节点不会在同一虚拟机管理程序主机上运行。

不支持以下 VMware 功能：

* 容错（ FT ）
* 虚拟数据存储库（ VVol ）




== 配置要求

如果您计划在外部存储阵列（ iSCSI ，光纤通道，以太网光纤通道）上使用 VMFS 数据存储库，则必须先创建 VMFS 存储池，然后再将 ONTAP Select 配置为使用该存储。如果使用 NFS 数据存储库，则无需创建单独的 VMFS 数据存储库。所有 vSAN 数据存储库都必须在同一 ESXi 集群中定义。


CAUTION: 在配置主机或执行存储添加操作时，您必须为 VMware vSAN 或外部存储阵列上的每个数据存储库提供容量限制。您指定的容量必须在外部存储允许的存储限制范围内。如果在磁盘创建操作期间未提供容量限制或外部存储空间用尽，则会发生错误。



== 最佳实践

请参考可用的 VMware 文档，并遵循为 ESXi 主机确定的适用最佳实践。此外：

* 为 ONTAP Select 网络和外部存储（使用 iSCSI 或 NFS 时为 VMware vSAN 和通用存储阵列流量）定义专用网络端口，带宽和 vSwitch 配置
* 配置容量选项以限制存储利用率（ ONTAP Select 不能占用外部 vNAS 数据存储库的全部容量）
* 确保所有通用外部存储阵列尽可能使用可用的冗余和 HA 功能

