---
sidebar: sidebar 
permalink: task_cli_deploy_image_add.html 
keywords: administer, administering, cli, deploy, ontap select image, add 
summary: 您可以将 ONTAP Select 映像添加到 Deploy 管理实用程序实例中。安装映像后，您可以在部署 ONTAP Select 集群时使用它。 
---
= 添加要部署的 ONTAP Select 映像
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可以将 ONTAP Select 映像添加到 Deploy 管理实用程序实例中。安装映像后，您可以在部署 ONTAP Select 集群时使用它。



== 开始之前

总体而言，用于向 Deploy 实例添加 ONTAP Select 映像的过程包括四个步骤：

. 正在下载安装映像
. 将安装映像上传到 Deploy 虚拟机
. 正在添加安装映像
. 显示可用的安装映像


在将任何新的 ONTAP Select 映像添加到 Deploy 之前，您应先删除任何不需要的映像。


NOTE: 您只能添加版本早于 Deploy 实用程序实例附带的原始版本的 ONTAP Select 映像。不支持添加从 NetApp 获得的更高版本的 ONTAP Select 。



== 正在下载安装映像

要开始向 Deploy 实用程序实例添加 ONTAP Select 映像的过程，您必须从 NetApp 支持站点下载此安装映像。ONTAP Select 安装映像的格式为一个压缩文件。

.步骤
. 使用 Web 浏览器访问 NetApp 支持站点，然后单击 * 支持快速链接 * 。
. 单击 * 首要任务 * 下的 * 下载软件 * 并登录到站点。
. 单击 * 查找您的产品 * 。
. 向下滚动并单击 * ONTAP Select * 。
. 在 * 其他可用 Select 软件 * 下，单击 * 部署升级，节点升级，映像安装 * 。
. 选择所需版本的升级软件包。
. 查看最终用户许可协议（ EULA ），然后单击 * 接受并继续 * 。
. 选择并下载相应的软件包，根据需要对环境中的所有提示做出响应。




== 将安装映像上传到 Deploy

获取 ONTAP Select 安装映像后，必须将此文件上传到 Deploy 虚拟机。

您必须在本地工作站上提供安装映像文件。您还必须具有 Deploy 管理员用户帐户的密码。

此任务介绍了一种将文件上传到 Deploy 虚拟机的方法。可能还有其他更适合您的环境的选项。

.步骤
. 在本地工作站上的命令 Shell 中，将映像文件上传到 Deploy 虚拟机。
+
示例

+
....
scp image_v_93_install_esx.tgz admin@10.234.81.101:/home/admin (provide password when prompted)
....
+
示例

+
....
sftp admin@10.234.81.101 (provide password when prompted)
put image_v_93_install_esx.tgz
exit
....


节点安装文件存储在管理员用户的主目录中。



== 正在添加安装映像

您可以将 ONTAP Select 安装映像添加到 Deploy 映像目录中，以便在部署新集群时可以使用该映像。

您必须知道此安装映像文件位于 Deploy 实用程序虚拟机上的哪个目录中。假定文件位于管理员的主目录中。

.步骤
. 使用管理员（ admin ）帐户使用 SSH 登录到 Deploy 实用程序命令行界面。
. 启动 Bash Shell ：
+
`shell bash`

. 将安装映像文件置于映像目录中。
+
示例 `tar -xf image_v_93_install_esx.tgz -C /opt/netapp/images/`





== 显示可用的安装映像

您可以显示部署新集群时可用的 ONTAP Select 映像。

.步骤
. 在 Deploy 实用程序虚拟机上访问联机文档网页，并使用管理员（ admin ）帐户登录：
+
` http://<FQDN|IP_ADDRESS>/api/ui`

+
使用 Deploy 虚拟机的域名或 IP 地址。

. 导航到页面底部，单击 * 部署 * ，然后单击 * 获取 /images* 。
. 单击 * 试用！ * 以显示可用的 ONTAP Select 映像。
. 确认所需的映像可用。

