---
sidebar: sidebar 
permalink: task_vpi_manually_remove.html 
keywords: vcenter, plug-in, vcenter plug-in, deploy plug-in, vcenter, remove, removing, manually removing 
summary: 您可以从 vCenter Server 中手动删除 Deploy 插件。 
---
= 从 vCenter 中手动删除 Deploy 插件
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可以从 vCenter Server 中手动删除 Deploy 插件。



== 开始之前

您应始终先使用 VMware 受管对象浏览器（ MOB ）删除此插件，然后再从 vCenter Server 中的 vSphere 目录中删除此插件。

在多种情况下，您必须手动删除此插件：

* 已使用 Deploy 实用程序原生 用户界面删除此插件，但无法重新启动 vCenter 服务器。
* 已停用 Deploy 实用程序，但未删除此插件。




== 使用 VMware MOB 删除此插件

MOB 是一个 VMware 应用程序，可用于查看和管理 VMware vCenter 服务器上的对象。您可以使用 MOB 删除 Deploy vCenter 插件。

.步骤
. 使用浏览器访问 vCenter 服务器上的 MOB 并登录：
+
` https://<FQDN_or_IP-address>/mob`

. 单击 * 内容 * ，然后单击 * 扩展管理器 * 。
. 根据全名确认要删除的扩展名是否存在：
+
`com.netapp.selectdeploy`

. 单击 * 注销扩展 * 。
. 键入扩展名的名称，然后单击 * InvokeMethod* 。


.结果
此插件将从扩展名列表中删除。



== 从 vSphere UI 文件夹中删除此插件

您应检查 vCenter 服务器上的 vSphere UI 目录，如果找到 Deploy 插件，则应将其删除。

.开始之前
您必须具有 vCenter Server 上根帐户的密码。您应使用 vSphere MOB 删除此插件。

.步骤
. 使用 SSH 访问 vCenter Server 并登录：
+
`ssh root@ <FQDN_OR_IP-address>`

. 键入 *shell* 并按 * Enter * 启动 Bash shell 。
. 导航到 vsphere-UI 服务的 `vsphere-client-serenity` 目录：
+
`cd /etc/vmware/vsphere-ui/vc-packages/vsphere-client-serenity`

. 确定是否存在必须删除的格式为 `com.netapp.selectdeploy` 的目录：
+
`ls -al`

. 停止 HTML5 vsphere-UI Web 客户端：
+
`sservice-control —停止 vsphere-ui`

. 删除包含 UI 扩展的目录：
+
`rm -rf com.netapp.selectdeploy-1.0.0`

. 重新启动 HTML5 vsphere-UI Web 客户端：
+
`sservice-control —启动 vsphere-ui`



.完成后
重新启动 Deploy 插件并使其可用可能需要几分钟时间。



== 从 vSphere 客户端文件夹中删除此插件

您应检查 vCenter 服务器上的 vSphere Client 目录，如果找到 Deploy 插件，则应将其删除。虽然 Deploy 插件不使用闪存，但最佳做法是在删除插件操作步骤 时检查此目录。

.开始之前
您必须具有 vCenter Server 上根帐户的密码。您应使用 vSphere MOB 删除此插件，并从 vSphere UI 目录中删除此插件。

.步骤
. 使用 SSH 访问 vCenter Server 并登录：
+
`ssh root@ <FQDN_OR_IP-address>`

. 键入 *shell* 并按 * Enter * 启动 Bash shell 。
. 导航到 vsphere-Client 服务的 `vsphere-client-serenity` 目录：
+
`cd /etc/vmware/vsphere-client/vc-packages/vsphere-client-serenity`

. 确定是否存在必须删除的格式为 `com.netapp.selectdeploy` 的目录：
+
`ls -al`

. 停止 HTML5 vsphere-UI Web 客户端：
+
`sservice-control —停止 vsphere-client`

. 删除包含客户端扩展的目录：
+
`rm -rf com.netapp.selectdeploy-1.0.0`

. 重新启动 HTML5 vsphere-UI Web 客户端：
+
`sservice-control —启动 vsphere-client`



.完成后
重新启动 Deploy 插件并使其可用可能需要几分钟时间。
