---
sidebar: sidebar 
permalink: task_vpi_deploy_cluster.html 
keywords: vcenter, plug-in, vcenter plug-in, deploy plug-in, deploy cluster, deploying cluster, create cluster, creating cluster 
summary: 您可以通过 vSphere Web 用户界面使用 Deploy vCenter 插件来部署 ONTAP Select 集群。 
---
= 部署 ONTAP Select 集群
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可以通过 vSphere Web 用户界面使用 Deploy vCenter 插件来部署 ONTAP Select 集群。



== 开始之前

在部署 ONTAP Select 集群之前，您应准备使用 Deploy vCenter 插件。



=== 适合各种规模的集群的常见准备工作

无论集群大小如何，您都需要执行以下几个步骤：

* 阅读 _Getting Started_ 一节，熟悉 Deploy vCenter 插件。
* 确保 ONTAP Select Deploy 管理实用程序已安装并正在运行。
* 安装 Deploy vCenter 插件。
* 准备要运行 ONTAP Select 集群的虚拟机管理程序主机。
* 为集群中的一个或多个节点获取所需的存储许可证文件。
* 获取以下帐户的凭据：
+
** 部署管理员帐户
** 有权访问此插件的 vCenter 帐户


* 如果需要，请在 Windows 证书管理器上以 " 可信根证书颁发机构 " 的身份安装 Deploy SSL 证书。
* 确保 Deploy 实用程序可以通过网络访问 vCenter Server 上的端口 443 。




=== 多节点集群的其他准备工作

除了常见准备工作之外，在部署多节点集群之前，您还应熟悉 Deploy 网络检查程序。



== 添加虚拟机管理程序主机

您可以将虚拟机管理程序主机添加到 Deploy 实用程序中，以便在部署集群之前运行 ONTAP Select 节点。如果需要，您可以在集群创建对话框中添加主机。

您应查看部署 ONTAP Select 集群的准备情况。

您可以根据集群大小添加一个或多个主机。

.步骤
. 使用浏览器通过 vSphere HTML5 登录到 vCenter Server 。
. 在工具栏中，单击 * 菜单 * ，然后单击 * 全局清单列表 * 。
. 在左侧窗格中，单击 * ONTAP Select Deploy * ，然后单击 * 主机 * 选项卡。
. 单击右侧的 * 添加 * 。
. 提供主机的主机名或 IP 地址，然后单击 * 添加 * 或 * 添加并退出 * 。




== 创建单节点集群

您可以通过 vSphere Web Client 使用 VMware vCenter 插件来部署由单个节点组成的 ONTAP Select 集群。

您应查看准备部署 ONTAP Select 集群和添加虚拟机管理程序主机。您可以在创建集群之前或在创建单节点集群过程中添加要运行 ONTAP Select 节点的主机。

.步骤
. 使用浏览器通过 vSphere HTML5 登录到 vCenter Server 。
. 单击顶部的 * 菜单 * ，然后单击 * 全局清单列表 * 。
. 单击左侧窗格中的 * ONTAP Select Clusters* ，然后单击 * 新建 ONTAP Select * 。
+
如果您之前未接受 SSL 证书，请单击警告消息中的 IP 链接并接受此证书。然后，返回到您的 vCenter 页面并单击警告消息中的链接以重新加载此页面。

. 在 * 新建 ONTAP Select 集群 * 页面上，输入集群详细信息并单击 * 完成 * 。
. 在 * 节点设置 * 部分中，提供配置并选择许可证。
+
如果需要，您可以更改默认节点名称并上传新许可证。

. 在 * 虚拟机管理程序和网络 * 部分中，选择实例类型，主机和网络。
+
您可以根据需要添加主机。节点的许可证必须满足或超过实例类型。

. 在 * 存储 * 部分中，选择存储容量和存储池。
+
使用高级许可证时，您可以选择启用软件 RAID 。

. 单击 * 完成 * 并查看集群的配置。
+
您可以根据需要在每个部分中单击编辑来更改配置。

. 单击 * 下一步 * 。
. 提供 ONTAP 管理员密码并单击 * 创建集群 * 以开始集群创建过程，然后单击确认弹出窗口中的 * 确定 * 。
+
创建集群可能需要长达 30 分钟的时间。

. 刷新页面并选择新集群，然后单击 * 摘要 * 和 * 详细信息 * 以监控多步集群创建过程。
+

TIP: 如果集群创建操作已启动，但无法完成，则不会注册您定义的 ONTAP 管理密码。在这种情况下，您可以使用密码 `changeme123` 和 `admin` 帐户访问 ONTAP Select 集群的管理界面。



.完成后
* 确认已启用 ONTAP Select AutoSupport 功能。
* 备份 ONTAP Select Deploy 配置数据。




== 创建多节点集群

您可以通过 vSphere Web Client 使用 VMware vCenter 插件来部署由多个节点组成的 ONTAP Select 集群。

您应查看准备部署 ONTAP Select 集群和添加虚拟机管理程序主机。您可以在创建集群之前或在创建多节点集群过程中添加要运行 ONTAP Select 节点的主机。

ONTAP Select 多节点集群包含偶数个节点。节点始终以 HA 对的形式加入。

.步骤
. 使用浏览器通过 vSphere HTML5 登录到 vCenter Server 。
. 单击顶部的 * 菜单 * ，然后单击 * 全局清单列表 * 。
. 单击左侧窗格中的 * ONTAP Select Clusters* ，然后单击 * 新建 ONTAP Select *
+
如果您之前未接受 SSL 证书，请单击警告消息中的 IP 链接并接受此证书。然后，返回到您的 vCenter 页面并单击警告消息中的链接以重新加载此页面。

. 在 * 新建 ONTAP Select 集群 * 页面上，输入集群详细信息并单击 * 完成 * 。
+
除非您有理由设置集群 MTU 大小，否则应接受默认值并允许 Deploy 根据需要进行任何调整。

. 在 * 节点设置 * 部分中，为 HA 对中的两个节点提供配置并选择许可证。
+
您可以根据需要更改默认节点名称并上传新许可证。

. 在 * 虚拟机管理程序和网络 * 部分中，选择每个节点的实例类型，主机和网络。
+
您可以根据需要添加主机。您必须选择三个网络。内部网络不能与管理网络或数据网络相同。节点的许可证必须满足或超过实例类型。

. 在 * 存储 * 部分中，选择存储容量和存储池。
+
使用高级许可证时，您可以选择启用软件 RAID 。

. 如果集群有四个或更多节点，则必须按照与第一个 HA 对相同的步骤配置其他 HA 对中的节点。
. 单击 * 完成 * 并查看集群的配置。
+
您可以根据需要在每个部分中单击 * 编辑 * 来更改配置。

. （可选）运行网络连接检查程序以测试内部集群网络上节点之间的连接。
. 单击 * 下一步 * 。
. 提供 ONTAP 管理员密码并单击 * 创建集群 * 以开始集群创建过程，然后单击确认弹出窗口中的 * 确定 * 。
+
创建集群可能需要长达 30 分钟的时间。

. 刷新页面并选择新集群，然后单击 * 摘要 * 和 * 详细信息 * 以监控多步集群创建过程。
+

TIP: 如果集群创建操作已启动，但无法完成，则不会注册您定义的 ONTAP 管理密码。在这种情况下，您可以使用密码 `changeme123` 和 `admin` 帐户访问 ONTAP Select 集群的管理界面。



.完成后
* 确认已启用 ONTAP Select AutoSupport 功能。
* 备份 ONTAP Select Deploy 配置数据。

