---
sidebar: sidebar 
permalink: task_vpi_adm_support.html 
keywords: vcenter, plug-in, vcenter plug-in, deploy plug-in, administer, administering, diagnostics, support 
summary: 在管理 ONTAP Select 过程中，您可以执行多项相关的诊断和支持任务。 
---
= 诊断和支持
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
在管理 ONTAP Select 过程中，您可以执行多项相关的诊断和支持任务。



== 显示系统设置

您可以通过 vCenter 插件查看 Deploy 管理实用程序的基本设置。

.步骤
. 单击 * 全局清单列表 * 窗格中的 * ONTAP Select Deploy * 。
. 单击 * 管理 * 选项卡。
. 展开 * 系统 * 选项，然后单击 * 设置 * 。
. 根据需要更新系统配置，然后单击 * 保存 * 。




== 显示事件消息

Deploy 管理实用程序包含一个事件日志记录工具，可提供有关系统活动的信息。您可以通过 Deploy 插件查看事件日志的内容来调试任何问题，也可以在支持人员要求时查看这些内容。

.关于此任务
您可以根据以下几个特征筛选事件消息列表：

* 类别
* Type
* 级别
* 实例


.步骤
. 单击 * 全局清单列表 * 窗格中的 * ONTAP Select Deploy * 。
. 单击 * 管理 * 选项卡。
. 展开 * 事件 * 选项，然后单击 * 部署 * 。
. 或者，也可以单击筛选并创建一个筛选器来限制显示的事件消息。




== 启用AutoSupport

AutoSupport 是 NetApp 用于支持 ONTAP Select 的主要故障排除工具。您可以根据需要启用或禁用 AutoSupport 功能。

.关于此任务
部署新集群后，您应确保已启用 AutoSupport 。只能在必要时禁用 AutoSupport 。如果禁用 AutoSupport ，则仍会收集数据，但不会将其传输到 NetApp 。

.步骤
. 单击 * 全局清单列表 * 窗格中的 * ONTAP Select Deploy * 。
. 单击 * 管理 * 选项卡。
. 展开 * AutoSupport 配置 * 选项，然后单击 * 配置 *
. 根据需要启用或禁用 AutoSupport 。




== 生成AutoSupport软件包

Deploy vCenter 插件可以生成 AutoSupport 软件包。您应生成软件包以调试问题，或者在支持人员要求时生成软件包。

.关于此任务
您可以生成以下 AutoSupport 软件包：

* 部署日志由 ONTAP Select Deploy 实用程序创建的日志文件
* 对有关虚拟机管理程序主机和 ONTAP Select 节点的故障排除和调试信息进行故障排除
* 有关虚拟机管理程序主机和 ONTAP Select 节点的性能信息


.步骤
. 单击 * 全局清单列表 * 窗格中的 * ONTAP Select Deploy * 。
. 单击 * 管理 * 选项卡。
. 展开 * AutoSupport * 选项，然后单击 * 生成 * 。
. 选择类型并为软件包提供问题描述 或提供案例编号，然后单击 * 生成 AutoSupport * 。
. 在左侧窗格中，单击 * AutoSupport * 下的 * 历史记录 * 并找到软件包。
+
您可以根据需要单击 * 刷新 * 。



.完成后
您可以使用原生 Deploy 实用程序用户界面将 AutoSupport 软件包下载到您的工作站。您不能使用 Deploy vCenter 插件下载此软件包。
