---
sidebar: sidebar 
permalink: task_cli_connectivity.html 
keywords: administer, administering, cli, connectivity, network connectivity, network checker 
summary: 您可以测试内部集群网络上两个或多个 ONTAP Select 节点之间的网络连接。通常，您可以在部署多节点集群之前运行此测试，以检测可能发生原因 导致操作失败的问题。 
---
= 确认 ONTAP Select 节点之间的网络连接
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可以测试内部集群网络上两个或多个 ONTAP Select 节点之间的网络连接。通常，您可以在部署多节点集群之前运行此测试，以检测可能发生原因 导致操作失败的问题。

必须配置测试中包含的所有 ONTAP Select 节点并打开其电源。

每次启动测试时，系统都会在后台创建一个新的进程运行，并为其分配一个唯一的运行标识符。一次只能有一个运行处于活动状态。

此测试有两种模式可控制其运行：

* 快速此模式可执行基本的无中断测试。执行 ping 测试，同时测试网络 MTU 大小和 vSwitch 。
* 扩展此模式可对所有冗余网络路径执行更全面的测试。如果在活动 ONTAP Select 集群上运行此命令，则可能会影响集群的性能。



NOTE: 建议在创建多节点集群之前始终执行快速测试。成功完成快速测试后，您可以根据生产要求选择执行扩展测试。

.步骤
. 使用管理员帐户登录到 Deploy 实用程序命令行界面。
. 显示当前运行的网络连接检查程序，并验证是否没有处于活动状态的运行：
+
`network connectivation-check show`

. 启动网络连接检查程序，并在命令输出中记下运行标识符：
+
`network connectivity-check start -host-names hostnames -vswitch-type vSwitch_type-mode mode`

+
示例

+
[listing]
----
network connectivity-check start -host-names 10.234.81.14
10.234.81.15 -vswitch-type StandardVSwitch -mode quick
----
. 根据运行标识符监控网络连接检查程序的进度：
+
`network connectivity-check show -run-id run_ID`



网络连接检查程序通常会通过删除添加到 ONTAP 内部端口组的任何临时端口和 IP 地址来进行清理。但是，如果连接检查程序无法删除临时端口，则必须使用选项 ` -mode cleanup` 重新运行 CLI 命令来执行手动清理操作。如果不从 ONTAP 内部端口组中删除临时端口，则可能无法成功创建 ONTAP Select 虚拟机。
